DROP TABLE METADATA_DESTINATION;
DROP TABLE TRANSFORMATIONS;
DROP TABLE METADATA_SOURCE;
DROP TABLE DATA_GENERATOR;
DROP TABLE PEQS;
DROP TABLE JOINS;
DROP TABLE ERROR_MESSAGES;
DROP TABLE INTERFACE_ASSIGNED;
DROP TABLE SQL_TEXT;
DROP TABLE SOURCES;
DROP TABLE ASSIGNMENT;

CREATE TABLE
ASSIGNMENT 
(
COD NUMBER PRIMARY KEY,
ASSIGNMENT VARCHAR2(30)
);

CREATE TABLE SOURCES
(
COD NUMBER(5) PRIMARY KEY,
SOURCE_NAME VARCHAR(30),
OWNER VARCHAR(30),
DBLINK VARCHAR(30)
);




CREATE TABLE SQL_TEXT
(
COD NUMBER PRIMARY KEY,
SQL_TEXT VARCHAR2(4000),
SQL_TYPE VARCHAR2(1)
);

CREATE TABLE INTERFACE_ASSIGNED
(
COD NUMBER(5),
COD_ASSIGNMENT NUMBER REFERENCES ASSIGNMENT,
INTERFC VARCHAR2(30),
INTERFC_ALIAS VARCHAR2(30),
COD_EXT NUMBER(5) REFERENCES SQL_TEXT,
INTERFC_SEPARATOR VARCHAR2(30),
VARIABLES VARCHAR(4000),
SRC_STM_CODE VARCHAR(30),
COD_SOURCE NUMBER REFERENCES SOURCES,
SOURCE_GEN_FLG VARCHAR2(1),
CONSTRAINT VALIDATION_PK PRIMARY KEY (COD,COD_ASSIGNMENT)
);



CREATE TABLE JOINS
(
COD NUMBER PRIMARY KEY,
JOIN_QUERY NUMBER REFERENCES SQL_TEXT,
HINT_QUERY NUMBER REFERENCES SQL_TEXT,
SUB_QUERY  NUMBER REFERENCES SQL_TEXT,
COND_QUERY NUMBER REFERENCES SQL_TEXT,
SELECT_QUERY NUMBER REFERENCES SQL_TEXT,
TYPE_JOIN VARCHAR2(30),
TYPE_JOIN_ALIAS VARCHAR2(30),
TYPE_JOIN_PREV VARCHAR2(30)

);


CREATE TABLE PEQS
(
COD NUMBER PRIMARY KEY,
SOURCE_APP_COD VARCHAR2(30),
DESTINATION_APP_COD VARCHAR2(30),
TIPOLOGY_COD VARCHAR2(30),
SOCIETY_COD VARCHAR2(30),
COD_JOIN NUMBER(5) REFERENCES JOINS,
COD_JOIN_EXT NUMBER(5) REFERENCES JOINS
);

CREATE TABLE ERROR_MESSAGES
(
COD NUMBER(5),
COD_ASSIGNMENT NUMBER REFERENCES ASSIGNMENT,
MSG_TEXT VARCHAR(4000),
CONSTRAINT ERROR_MESSAGES_PK PRIMARY KEY (COD,COD_ASSIGNMENT)
);




CREATE TABLE TRANSFORMATIONS
(
COD NUMBER PRIMARY KEY,
VAL_TYPE NUMBER(5) REFERENCES SQL_TEXT,
VAL_PARAM VARCHAR2(4000),
TRANS_TYPE NUMBER(5) REFERENCES SQL_TEXT,
TRANS_PARAM VARCHAR(4000)
);

CREATE TABLE METADATA_DESTINATION
(
COD NUMBER(5),
COD_ASSIGNMENT NUMBER(5),
COD_INTERFACE_ASSIGNED NUMBER(5),
COLUMN_NAME VARCHAR2(30),
COLUMN_TYPE VARCHAR2(30),
COLUMN_LENGTH NUMBER(5),
COLUMN_PRECISION NUMBER(5),
ANT_PARAM VARCHAR(4000),
COD_PEQ NUMBER(5) REFERENCES PEQS,
COD_JOIN NUMBER(5) REFERENCES JOINS,
SEVERITY VARCHAR2(30),
COD_TRANSFORMATIONS NUMBER(5) REFERENCES TRANSFORMATIONS,
CONSTRAINT METADATA_DESTINATION_FK FOREIGN KEY (COD_INTERFACE_ASSIGNED,COD_ASSIGNMENT) REFERENCES INTERFACE_ASSIGNED(COD,COD_ASSIGNMENT),
CONSTRAINT METADATA_DESTINATION_PK PRIMARY KEY (COD,COD_INTERFACE_ASSIGNED,COD_ASSIGNMENT)
);

CREATE TABLE DATA_GENERATOR
(
COD NUMBER(5) PRIMARY KEY,
EXT_TYPE NUMBER(5) REFERENCES SQL_TEXT,
TRANS_TYPE NUMBER(5) REFERENCES SQL_TEXT, 
PEQ_TYPE NUMBER(5) REFERENCES PEQS
);

CREATE TABLE METADATA_SOURCE
(
COD NUMBER(5) REFERENCES SOURCES,
COLUMN_ID NUMBER(5),
COLUMN_NAME VARCHAR2(30),
COLUMN_LENGTH NUMBER(5),
COLUMN_PRECISION NUMBER(5),
COLUMN_TYPE VARCHAR2(30),
COD_EXT NUMBER(5) REFERENCES DATA_GENERATOR,
COD_EXT_ERR NUMBER(5) REFERENCES DATA_GENERATOR,
SOURCE_PARAM VARCHAR2(4000),
CONSTRAINT METADATA_SOURCE_PK PRIMARY KEY (COD,COLUMN_ID)
);
