CREATE TABLE ALL_TAB_COLUMNS_DMRFN 
(
OWNER VARCHAR2(128),
TABLE_NAME VARCHAR2(128),
COLUMN_NAME VARCHAR2(128),
DATA_TYPE VARCHAR2(128),
DATA_TYPE_MOD VARCHAR2(3),
DATA_TYPE_OWNER VARCHAR2(128),
DATA_LENGTH NUMBER(22),
DATA_PRECISION NUMBER(22),
DATA_SCALE NUMBER(22),
NULLABLE VARCHAR2(1),
COLUMN_ID NUMBER(22),
DEFAULT_LENGTH NUMBER(22),
DATA_DEFAULT VARCHAR(256),
NUM_DISTINCT NUMBER(22),
LOW_VALUE RAW(1000),
HIGH_VALUE RAW(1000),
DENSITY NUMBER(22),
NUM_NULLS NUMBER(22),
NUM_BUCKETS NUMBER(22),
LAST_ANALYZED DATE,
SAMPLE_SIZE NUMBER(22),
CHARACTER_SET_NAME VARCHAR2(44),
CHAR_COL_DECL_LENGTH NUMBER(22),
GLOBAL_STATS VARCHAR2(3),
USER_STATS VARCHAR2(3),
AVG_COL_LEN NUMBER(22),
CHAR_LENGTH NUMBER(22),
CHAR_USED VARCHAR2(1),
V80_FMT_IMAGE VARCHAR2(3),
DATA_UPGRADED VARCHAR2(3),
HISTOGRAM VARCHAR2(15),
DEFAULT_ON_NULL VARCHAR2(3),
IDENTITY_COLUMN VARCHAR2(3),
EVALUATION_EDITION VARCHAR2(128),
UNUSABLE_BEFORE VARCHAR2(128),
UNUSABLE_BEGINNING VARCHAR2(128)
)
;

SELECT 'DROP TABLE '||OWNER||'.'||TABLE_NAME||';' FROM ALL_TABLES@DLKDMR
where   owner = upper('DMRFN');
select  table_name y,
        0 x,
        'CREATE TABLE '||OWNER||'.' ||
        rtrim(table_name) ||
        '('
from    ALL_TABLES@DLKDMR
where   owner = upper('DMRFN')
union
select  tc.table_name y,
        column_id x,
        REPLACE(decode(column_id,1,'    ','   ,')||
        rtrim(column_name)|| CHR(9) || CHR(9) ||
        rtrim(data_type) ||
        rtrim(decode(data_type,'DATE',null,'LONG',null,
               'NUMBER',decode(to_char(data_precision),null,null,'('),
               '(')) ||
        rtrim(decode(data_type,
               'DATE',null,
               'CHAR',data_length,
               'VARCHAR2',data_length,
               'NVARCHAR2', DECODE(data_length,4000,1000,data_length),
               'CHAR',data_length,
               'NUMBER',decode(to_char(data_precision),null,null,
                 to_char(data_precision) || ',' || to_char(data_scale)),
               'LONG',null,
               '******ERROR')) ||
        rtrim(decode(data_type,'DATE',null,'LONG',null,
               'NUMBER',decode(to_char(data_precision),null,null,')'),
               ')')) || CHR(9) || CHR(9) ||
        CASE WHEN  tc.data_default is not null then ' DEFAULT '||tc.data_default end || chr(9)||
        rtrim(decode(nullable,'N','NOT NULL',null)),'(******ERROR)')
        
from    ALL_TAB_COLUMNS_DMRFN tc
        
where   
     tc.owner = upper('DMRFN')
union
select  table_name y,
        999999 x,
        ');'  || CHR(10)
      /*  ||'  STORAGE('                                   || CHR(10)
        ||'  INITIAL '    || initial_extent              || CHR(10)
        ||'  NEXT '       || next_extent                 || CHR(10)
        ||'  MINEXTENTS ' || min_extents                 || CHR(10)
        ||'  MAXEXTENTS ' || max_extents                 || CHR(10)
        ||'  PCTINCREASE '|| pct_increase                || ')' ||CHR(10)
        ||'  INITRANS '   || ini_trans                   || CHR(10)
        ||'  MAXTRANS '   || max_trans                   || CHR(10)
        ||'  PCTFREE '    || pct_free                    || CHR(10)
        ||'  PCTUSED '    || pct_used                    || CHR(10)
        ||'  PARALLEL (DEGREE ' || rtrim(DEGREE) || ') ' || CHR(10)
        ||'  TABLESPACE ' || rtrim(tablespace_name)      ||CHR(10)*/
        ||'/'||CHR(10)||CHR(10)
from    ALL_TABLES@DLKDMR
where   owner = upper('DMRFN')
order by 1,2;

SELECT 
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE('CREATE <U> INDEX <O>.<I> ON <O>.<T> (<I_COL>);'
,'<O>',ALL_IND_COLUMNS.INDEX_OWNER)
,'<I>',ALL_IND_COLUMNS.INDEX_NAME)
,'<T>',ALL_IND_COLUMNS.TABLE_NAME)
,'<U>',REPLACE(ALL_INDEXES.UNIQUENESS,'NONUNIQUE'))

,'<I_COL>',LISTAGG( ALL_IND_COLUMNS.COLUMN_NAME||' '||ALL_IND_COLUMNS.DESCEND, ',') WITHIN GROUP (ORDER BY ALL_IND_COLUMNS.COLUMN_POSITION)) A
FROM
ALL_IND_COLUMNS@DLKDMR
INNER JOIN
ALL_INDEXES@DLKDMR ON
ALL_IND_COLUMNS.INDEX_NAME=ALL_INDEXES.INDEX_NAME
WHERE
ALL_IND_COLUMNS.TABLE_OWNER='DMRFN' AND
ALL_INDEXES.TABLE_OWNER='DMRFN'
GROUP BY ALL_IND_COLUMNS.INDEX_OWNER
,ALL_IND_COLUMNS.INDEX_NAME
,ALL_IND_COLUMNS.TABLE_NAME
,ALL_INDEXES.UNIQUENESS
;


SELECT 
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE('ALTER TABLE <O>.<T> ADD CONSTRAINT <C> PRIMARY KEY ( <COLS> ) <US>;'
,'<T>',ALL_CONSTRAINTS.TABLE_NAME)
,'<US>',CASE WHEN ALL_CONSTRAINTS.INDEX_NAME IS NOT NULL THEN 'USING INDEX <O>.'||ALL_CONSTRAINTS.INDEX_NAME END)
,'<O>',ALL_CONSTRAINTS.OWNER)
,'<C>',ALL_CONSTRAINTS.CONSTRAINT_NAME),'<COLS>',LISTAGG(ALL_CONS_COLUMNS.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY 1))

FROM
ALL_CONSTRAINTS@DLKDMR
INNER JOIN 
ALL_CONS_COLUMNS@DLKDMR ON
ALL_CONS_COLUMNS.TABLE_NAME=ALL_CONSTRAINTS.TABLE_NAME AND
ALL_CONS_COLUMNS.OWNER=ALL_CONSTRAINTS.OWNER AND
ALL_CONS_COLUMNS.CONSTRAINT_NAME=ALL_CONSTRAINTS.CONSTRAINT_NAME
WHERE CONSTRAINT_TYPE='P' AND ALL_CONS_COLUMNS.OWNER='DMRFN' AND ALL_CONSTRAINTS.TABLE_NAME NOT LIKE 'BIN$%'
GROUP BY
ALL_CONSTRAINTS.TABLE_NAME,ALL_CONSTRAINTS.OWNER,ALL_CONSTRAINTS.CONSTRAINT_NAME,ALL_CONSTRAINTS.INDEX_NAME;







SELECT 
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE('ALTER TABLE <O>.<T> ADD CONSTRAINT <C> FOREIGN KEY ( <COLS> ) REFERENCES <O>.<T_R> ( <COLS_R> );'
,'<T>',ALL_CONSTRAINTS.TABLE_NAME)
,'<O>',ALL_CONSTRAINTS.OWNER)
,'<C>',ALL_CONSTRAINTS.CONSTRAINT_NAME)
,'<COLS>',LISTAGG(ALL_CONS_COLUMNS.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY 1))
,'<T_R>',PKS.TABLE_NAME)
,'<COLS_R>',PKS.PKS)


FROM
ALL_CONSTRAINTS@DLKDMR
INNER JOIN 
ALL_CONS_COLUMNS@DLKDMR ON
ALL_CONS_COLUMNS.TABLE_NAME=ALL_CONSTRAINTS.TABLE_NAME AND
ALL_CONS_COLUMNS.OWNER=ALL_CONSTRAINTS.OWNER AND
ALL_CONS_COLUMNS.CONSTRAINT_NAME=ALL_CONSTRAINTS.CONSTRAINT_NAME
LEFT JOIN
(
SELECT 
ALL_CONSTRAINTS.TABLE_NAME,
ALL_CONSTRAINTS.CONSTRAINT_NAME,
LISTAGG(ALL_CONS_COLUMNS.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY 1) PKS
FROM
ALL_CONSTRAINTS@DLKDMR
INNER JOIN 
ALL_CONS_COLUMNS@DLKDMR ON
ALL_CONS_COLUMNS.TABLE_NAME=ALL_CONSTRAINTS.TABLE_NAME AND
ALL_CONS_COLUMNS.OWNER=ALL_CONSTRAINTS.OWNER AND
ALL_CONS_COLUMNS.CONSTRAINT_NAME=ALL_CONSTRAINTS.CONSTRAINT_NAME
WHERE CONSTRAINT_TYPE='P' AND ALL_CONS_COLUMNS.OWNER='DMRFN' AND ALL_CONSTRAINTS.TABLE_NAME NOT LIKE 'BIN$%'
GROUP BY
ALL_CONSTRAINTS.TABLE_NAME,ALL_CONSTRAINTS.OWNER,ALL_CONSTRAINTS.CONSTRAINT_NAME
)PKS ON 
PKS.CONSTRAINT_NAME=ALL_CONSTRAINTS.R_CONSTRAINT_NAME
WHERE CONSTRAINT_TYPE='R' AND ALL_CONS_COLUMNS.OWNER='DMRFN'
GROUP BY
ALL_CONSTRAINTS.TABLE_NAME,ALL_CONSTRAINTS.OWNER,ALL_CONSTRAINTS.CONSTRAINT_NAME,PKS.TABLE_NAME,PKS.PKS;


select UPPER('Create Sequence '||SEQUENCE_OWNER||'.'||sequence_name||
       ' increment by '||increment_by||
       ' start with '||'1'||
       ' maxvalue '||max_value||
       decode(cycle_flag,'N',' NOCYCLE ',' CYCLE ')||
       decode(cache_size,0,'NOCACHE ','CACHE '||cache_size))||';'
 from ALL_sequences@DLKDMR WHERE SEQUENCE_OWNER='DMRFN';
 
 
SELECT * FROM ALL_TAB_COLUMNS@DLKDMR WHERE OWNER='DMRFN';




