DROP TABLE DMRPMCOR.TMP_PST_ADR;
DROP TABLE DMRPMCOR.TMP_cstmr;
DROP TABLE DMRPMCOR.TMP_ORG_PRFL;
DROP TABLE DMRPMCOR.TMP_ORG;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP6;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP5;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP4;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP3;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP2;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP;
DROP TABLE DMRPMCOR.TMP_IP;
DROP TABLE DMRPMCOR.TMP_IDV;
DROP TABLE DMRPMCOR.TMP_CST_FRGN_CCY_OPRN;
DROP TABLE DMRPMCOR.TMP_LO_ADR;
DROP TABLE DMRPMCOR.TMP_LO;
DROP TABLE DMRPMCOR.TMP_IP_X_LO_RLTNP;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP6_DRP;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP5_DRP;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP4_DRP;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP3_DRP;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP2_DRP;
DROP TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP1_DRP;
DROP TABLE DMRPMCOR.TMP_IDV_PRFL;
DROP TABLE DMRPMCOR.TMP_ELC_ADR;
DROP TABLE DMRPMCOR.STM_VAR;
DROP TABLE DMRPMCOR.RATE;
DROP TABLE DMRPMCOR.PST_ADR;
DROP TABLE DMRPMCOR.PRDC_ITRV;
DROP TABLE DMRPMCOR.OU;
DROP TABLE DMRPMCOR.ORG_PRFL;
DROP TABLE DMRPMCOR.ORG;
DROP TABLE DMRPMCOR.MSR_PRD;
DROP TABLE DMRPMCOR.LO_X_SRC_STM_RLTNP;
DROP TABLE DMRPMCOR.LO_X_LO_RLTNP;
DROP TABLE DMRPMCOR.LO_X_CL_RLTNP;
DROP TABLE DMRPMCOR.LO;
DROP TABLE DMRPMCOR.IP_X_TX_TP_RLTNP;
DROP TABLE DMRPMCOR.IP_X_SRC_STM_RLTNP;
DROP TABLE DMRPMCOR.IP_X_LO_RLTNP;
DROP TABLE DMRPMCOR.IP_X_IP_RLTNP;
DROP TABLE DMRPMCOR.IP;
DROP TABLE DMRPMCOR.INT_RATE;
DROP TABLE DMRPMCOR.IDV_PRFL;
DROP TABLE DMRPMCOR.IDV;
DROP TABLE DMRPMCOR.EXG_RATE;
DROP TABLE DMRPMCOR.EMP;
DROP TABLE DMRPMCOR.ELC_ADR;
DROP TABLE DMRPMCOR.CTY_X_CCY_RLTNP;
DROP TABLE DMRPMCOR.CSTMR_X_OU_RLTNP;
DROP TABLE DMRPMCOR.CST_FRGN_CCY_OPRN;
DROP TABLE DMRPMCOR.CNL;
DROP TABLE DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP;
DROP TABLE DMRPMCOR.CL_X_OU_RLTNP;
DROP TABLE DMRPMCOR.CL_X_IP_RLTNP;
DROP TABLE DMRPMCOR.CL_X_CL_RLTNP;
DROP TABLE DMRPMCOR.CL_TSL;
DROP TABLE DMRPMCOR.CD;
DROP TABLE DMRPMCOR.CSTMR;
DROP TABLE DMRPMCOR.CL_VAL;
DROP TABLE DMRPMCOR.CL_SCM;
DROP TABLE DMRPMCOR.SRC_STM;

CREATE TABLE DMRPMCOR.CD(
    CNDTN_ID		NUMBER(9,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(30)			NOT NULL
   ,CNDTN_TP_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,EFF_DT		DATE			
   ,END_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.CL_SCM(
    CL_SCM_ID		NUMBER(9,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,CL_SUP_SCM_ID		NUMBER(9,0)		 DEFAULT -2	
   ,NUM_CODE_F		NUMBER(5,0)			
   ,CODE_LEN		NUMBER(5,0)			
   ,SCM_CODE		VARCHAR2(20)			NOT NULL
   ,SHRT_NM		VARCHAR2(40)			
   ,CL_SCM_NM		VARCHAR2(128)			
   ,LONG_NM		VARCHAR2(128)			
   ,EFF_DT		DATE			
   ,END_DT		DATE			
   ,MX_GEN_NO		NUMBER(5,0)			
   ,DSC		VARCHAR2(256)			
);
/


CREATE TABLE DMRPMCOR.CL_TSL(
    CL_TSL_ID		NUMBER(9,0)			NOT NULL
   ,LNG_ID		NUMBER(9,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,CL_NM		VARCHAR2(64)			
   ,CL_CD		VARCHAR2(20)			
   ,SHRT_NM		VARCHAR2(18)			
   ,DSC		VARCHAR2(256)			
);
/


CREATE TABLE DMRPMCOR.CL_VAL(
    CL_VAL_ID		NUMBER(9,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,CL_SCM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,CL_SCM_SEQ_NBR		NUMBER(5,0)			
   ,ROOT_CL_SCM_ID		NUMBER(9,0)		 DEFAULT -2	
   ,GRP_CL_ID		NUMBER(9,0)			
   ,EFF_DT		DATE			
   ,END_DT		DATE			
   ,CL_UTLZ_F		NUMBER(5,0)			
   ,CL_CD		VARCHAR2(50)			
   ,SHRT_NM		VARCHAR2(40)			
   ,GEN_NO		NUMBER(5,0)			
   ,CL_NM		VARCHAR2(256)			NOT NULL
   ,DSC		VARCHAR2(256)			
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(80)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
);
/


CREATE TABLE DMRPMCOR.CL_X_CL_RLTNP(
    SBJ_CL_ID		NUMBER(9,0)			NOT NULL
   ,OBJ_CL_ID		NUMBER(9,0)			NOT NULL
   ,CL_X_CL_RLTNP_TP_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,RANK		NUMBER(5,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,END_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.CL_X_IP_RLTNP(
    CV_ID		NUMBER(9,0)			NOT NULL
   ,IP_ID		NUMBER(9,0)			NOT NULL
   ,CL_X_IP_RLTNP_TP_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,RANK		NUMBER(5,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,SCOR_MSR		NUMBER(5,2)			
   ,END_DT		DATE			
   ,DSC		VARCHAR2(256)			
);
/


CREATE TABLE DMRPMCOR.CL_X_OU_RLTNP(
    CL_VAL_ID		NUMBER(9,0)			NOT NULL
   ,OU_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,RANK		NUMBER(5,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,CL_X_OU_RLTNP_TP_ID		NUMBER(9,0)			NOT NULL
   ,DSC		VARCHAR2(256)			
   ,END_DT		DATE			
   ,SCOR_MSR		NUMBER(5,2)			
   ,SRC_STM_ID		NUMBER(9,0)			NOT NULL
);
/


CREATE TABLE DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP(
    CSTMR_X_OU_RLTNP_ID		NUMBER(9,0)			NOT NULL
   ,CL_X_OU_X_CSTMR_RLTNP_TP_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,END_DT		DATE			
   ,CV_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
);
/


CREATE TABLE DMRPMCOR.CNL(
    CNL_ID		NUMBER(9,0)			NOT NULL
   ,CNL_TP_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,CNL_LCS_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CNL_NM		VARCHAR2(64)			
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(30)			NOT NULL
   ,CNL_CODE		VARCHAR2(20)			
   ,ALT_LNG_CNL_NM		VARCHAR2(64)			
   ,CNL_PRN_ID		NUMBER(9,0)		 DEFAULT -2	
);
/


CREATE TABLE DMRPMCOR.CST_FRGN_CCY_OPRN(
    CSTMR_ID		NUMBER(9,0)			NOT NULL
   ,FRGN_CCY_PD_TP_ID		NUMBER(9,0)			NOT NULL
   ,OPRN_FRGN_CCY_TP_ID		NUMBER(9,0)			NOT NULL
   ,FRGN_CCY_AC_NUM		VARCHAR2(20)			NOT NULL
   ,OPRN_FRGN_CCY_BNK_NM		VARCHAR2(60)			
   ,CITY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CITY_NM		VARCHAR2(80)			
   ,CTY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,FRGN_CCY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,FRGN_CCY_AV_AMT		NUMBER(24,4)			
   ,END_DT		DATE			
   ,EFF_DT		DATE			
   ,OPRN_FRGN_CCY_F_ID		NUMBER(9,0)		 DEFAULT -2	
);
/


CREATE TABLE DMRPMCOR.CSTMR(
    CSTMR_ID		NUMBER(9,0)			NOT NULL
   ,CSTMR_LCS_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CST_LCS_DT		DATE			
   ,CST_CGY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CST_CGY_DT		DATE			
   ,PRIM_BR_NO		VARCHAR2(20)			
   ,PRIM_BR_ID		NUMBER(9,0)		 DEFAULT -2	
   ,RLN_EP_DT		DATE			
   ,EFF_CST_DT		DATE			
   ,END_CST_DT		DATE			
   ,CST_MKT_SEG_DT		DATE			
   ,CSTMR_RAC_IND		VARCHAR2(5)			
   ,CSTMR_EB_CODE		NUMBER(9,0)			
   ,GEO_AREA_ID		NUMBER(9,0)		 DEFAULT -2	
   ,BSN_VTL_BR_F		NUMBER(5,0)			
   ,PSN_VTL_BR_F		NUMBER(5,0)			
   ,MGN_F		NUMBER(5,0)			
   ,NEED_LME_F		NUMBER(5,0)			
   ,CSTMR_MKT_SEG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,SLFT_RSK_RTG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CTC_CNL_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CTC_LO_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CTC_DT		DATE			
   ,CTC_TM		TIMESTAMP(6)			
   ,FND_ORIG_CTY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,FND_ORIG_CITY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,FND_ORIG_CITY_NM		VARCHAR2(80)			
   ,CSTMR_MKT_SUB_SEG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,AC_STMT_DLV_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,EMAIL_ADR_CTC_AHR_ID		NUMBER(9,0)		 DEFAULT -2	
   ,SMS_CTC_AHR_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IVC_VAL		NUMBER(9,0)			
   ,FRGN_EXG_BKR_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CSTMR_BNK_RSK_AHR_F		NUMBER(5,0)			
   ,FND_ORIG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PTY_ORIG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CST_RLTNP_ST_ID		NUMBER(9,0)		 DEFAULT -2	
   ,BLC_F		VARCHAR2(2)			
   ,CST_RLTNP_AVY_ST_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CITY_FILN_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CITY_FILN_NM		VARCHAR2(80)			
   ,CST_SPCL_PRGM_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,EXMPT_CASH_OPRN_STMT_ID		NUMBER(9,0)		 DEFAULT -2	
   ,FNC_IMT_PD_F_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CHKLST_VLD_DT		DATE			
   ,INTVN_LAW_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,SPCL_CR_ADMN_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PCRMT_PCS_CL_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CST_EMP_EXN_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,MAIN_EMAIL_ADR		VARCHAR2(241)			
   ,MAIN_WEBST_ADR		VARCHAR2(2048)			
   ,CST_PTNL_VAL_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CST_STRTG_VAL_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PAM_CODE		VARCHAR2(20)			
   ,UDT_DOC_FILLN_DT		DATE			
   ,EFF_LKG_DT		DATE			
   ,UDT_CNL_ID		NUMBER(9,0)		 DEFAULT -2	
   ,RET_AC_STMT_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,AST_MGT_F		VARCHAR2(2)			
   ,PRVT_SEG_F		VARCHAR2(2)			
   ,SOC_STL_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PBLC_EXD_FE_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PBLC_EXD_ID		NUMBER(9,0)		 DEFAULT -2	
   ,EFF_LKG_DT_FE		DATE			
   ,CSTMR_RTF_WHLD_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CSTMR_MKT_TRNSV_SEG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PPN_DT		DATE		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,PPN_TM		TIMESTAMP(6)		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,EFF_DT		DATE		 DEFAULT TO_DATE ('00010102', 'YYYYMMDD') 	NOT NULL
   ,MAIN_EMAIL_ADR_PER		VARCHAR2(256)			
   ,TOTAL_COST_ID		NUMBER(9,0)		 DEFAULT -2	
);
/


CREATE TABLE DMRPMCOR.CSTMR_X_OU_RLTNP(
    CSTMR_X_OU_RLTNP_ID		NUMBER(9,0)			NOT NULL
   ,CSTMR_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,OU_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,EFF_LKG_DT		DATE			
   ,EFF_DT		DATE			NOT NULL
   ,END_DT		DATE			
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,TDS_EXMPT_DT		DATE			
   ,CTC_CNL_ID		NUMBER(9,0)		 DEFAULT -2	
);
/


CREATE TABLE DMRPMCOR.CTY_X_CCY_RLTNP(
    CCY_ID		NUMBER(9,0)			NOT NULL
   ,CTY_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,DMST_CCY_F		NUMBER(5,0)			
   ,ITNL_CCY_F		NUMBER(5,0)			
   ,END_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.ELC_ADR(
    ELC_ADR_ID		NUMBER(9,0)			NOT NULL
   ,ELC_ADR_TP_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,EXN		VARCHAR2(10)			
   ,FULL_TEL_NO		VARCHAR2(30)			
   ,TEL_DVC_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,URL		VARCHAR2(2048)			
   ,EMAIL_ADR		VARCHAR2(241)			
   ,PPN_DT		DATE		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,PPN_TM		TIMESTAMP(6)		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,EFF_DT		DATE		 DEFAULT TO_DATE ('00010102', 'YYYYMMDD') 	NOT NULL
);
/


CREATE TABLE DMRPMCOR.EMP(
    EMP_ID		NUMBER(9,0)			NOT NULL
   ,EMP_NM		VARCHAR2(80)			
   ,EMPE_NO		VARCHAR2(30)			NOT NULL
   ,USR_ID		VARCHAR2(20)			
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(30)			NOT NULL
   ,EMP_LCS_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,EMP_DT		DATE			
   ,EMP_POS_NM		VARCHAR2(80)			
   ,EMP_POS_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,EMP_LCS_TP_DT		DATE			
   ,IDV_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,OU_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,NON_WAGE_SLRY_BNFT_AMT		NUMBER(24,4)			
   ,MAIN_MO_SLRY_AMT		NUMBER(24,4)			
   ,LBR_COST_FCTR		NUMBER(24,4)			
   ,SHR_SVC_F		CHAR(1)			
   ,ACG_OU_ID		NUMBER(9,0)		 DEFAULT -2	
);
/


CREATE TABLE DMRPMCOR.EXG_RATE(
    EXG_RATE_ID		NUMBER(9,0)			NOT NULL
   ,FRST_CCY_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,SCD_CCY_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,EXG_RATE_VAL_RATE		NUMBER(14,7)			
);
/


CREATE TABLE DMRPMCOR.IDV(
    IDV_ID		NUMBER(9,0)			NOT NULL
   ,GND_ID		NUMBER(9,0)		 DEFAULT -2	
   ,BRTH_DT		DATE			
   ,IDV_MAR_ST_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,SOCIO_ECN_CGY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IDV_IDY_CL_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CTF_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IDV_OCP_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IDV_EMP_ST_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IDV_HLT_ST_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CTY_BRTH_ID		NUMBER(9,0)		 DEFAULT -2	
   ,NM_INL		VARCHAR2(6)			
   ,GVN_NM		VARCHAR2(40)			
   ,IDV_EMP_DT		DATE			
   ,MDL_NM		VARCHAR2(40)			
   ,SURNM1		VARCHAR2(40)			
   ,SURNM2		VARCHAR2(40)			
   ,FULL_NM		VARCHAR2(256)			
   ,CITY_BRTH_ID		NUMBER(9,0)		 DEFAULT -2	
   ,EMPR_NM		VARCHAR2(40)			
   ,DEATH_ST_ID		NUMBER(9,0)		 DEFAULT -2	
   ,KNPD_F		VARCHAR2(2)			
   ,SBN_CODE		VARCHAR2(20)			
   ,EXL_RGSTY		VARCHAR2(30)			
   ,HOB		VARCHAR2(64)			
   ,SPRT		VARCHAR2(64)			
   ,MNOR_F		VARCHAR2(2)			
   ,CTY_BRTH_NM		VARCHAR2(80)			
   ,UCPBL_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,STDY_LVL_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PPN_DT		DATE		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,PPN_TM		TIMESTAMP(6)		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,EFF_DT		DATE		 DEFAULT TO_DATE ('00010102', 'YYYYMMDD') 	NOT NULL
);
/


CREATE TABLE DMRPMCOR.IDV_PRFL(
    IDV_ID		NUMBER(9,0)			NOT NULL
   ,DNMN_CCY_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,END_DT		DATE			
   ,MAIN_MO_INCM		NUMBER(24,4)			
   ,OTHR_MO_INCM		NUMBER(24,4)			
   ,TOT_MO_INCM		NUMBER(24,4)			
   ,TOT_MO_EXPND		NUMBER(24,4)			
   ,TOT_AST		NUMBER(24,4)			
   ,TOT_LBY		NUMBER(24,4)			
   ,TOT_EQTY		NUMBER(24,4)			
   ,ANUL_SALE_DT		DATE			
   ,ANUL_SALE_VOL		NUMBER(24,4)			
   ,MKT_SZ		NUMBER(24,4)			
   ,NBR_DPND_CHL		NUMBER(5,0)			
   ,EMP_CNT		NUMBER(9,0)			
   ,NET_WHRT		NUMBER(24,4)			
   ,NET_INCM		NUMBER(24,4)			
   ,INCM_FN		NUMBER(24,4)			
   ,EXPN_FN		VARCHAR2(5)			
);
/


CREATE TABLE DMRPMCOR.INT_RATE(
    INT_RATE_ID		NUMBER(9,0)			NOT NULL
   ,INT_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CR_DB_IND		VARCHAR2(1)			
   ,INT_CLC_PRD_ID		NUMBER(9,0)		 DEFAULT -2	
   ,EFF_RATE_PCT		NUMBER(12,8)			
   ,SPRD_RATE_PCT		NUMBER(12,8)			
);
/


CREATE TABLE DMRPMCOR.IP(
    IP_ID		NUMBER(9,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(30)			NOT NULL
   ,IP_TP_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,PRIM_RLN_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IP_NM		VARCHAR2(80)			
   ,SHRT_NM		VARCHAR2(40)			
   ,FI_F		NUMBER(5,0)			
   ,EFF_DT		DATE			
   ,END_DT		DATE			
   ,DSC		VARCHAR2(256)			
   ,COL_RSDNT_ID		NUMBER(9,0)		 DEFAULT -2	
   ,MON_RSK		NUMBER(5,0)			
   ,BSN_SECT_ID		NUMBER(9,0)		 DEFAULT -2	
   ,BSN_SUB_SECT_ID		NUMBER(9,0)		 DEFAULT -2	
   ,MON_RSK_CL		VARCHAR2(20)			
   ,ECN_AVY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,LGL_PRC_FLG		NUMBER(5,0)			
   ,CIIU_IDY_CL_ID		NUMBER(9,0)		 DEFAULT -2	
   ,SUB_CIIU_IDY_CL_ID		NUMBER(9,0)		 DEFAULT -2	
   ,BLCKLIST_ACTN_ID		NUMBER(9,0)		 DEFAULT -2	
   ,DOC_VLD_RSP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,VIN_RSK_FCTR_ID		NUMBER(9,0)		 DEFAULT -2	
   ,REG_INST_MOND_ID		NUMBER(9,0)		 DEFAULT -2	
   ,ORG_ENT_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,DCNT_STE_ENT_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,STE_ENT_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IP_TAX_RPT_ID		NUMBER(9,0)		 DEFAULT -2	
   ,TAX_SLF_WHLD_ID		NUMBER(9,0)		 DEFAULT -2	
   ,TPY_CLSS_ID		NUMBER(9,0)		 DEFAULT -2	
   ,TPY_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IVA_RSPL_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IVA_RGM_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,WHLD_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,NON_CMRCL_RLV_F		VARCHAR2(2)			
   ,PREF_CTC_MTH_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PRIM_RLN_TP_DT		DATE			
   ,INR_IP_CR_RSK_RTG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,LAST_UDT_DT		DATE			
   ,IP_GRP_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,COM_ATTD_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,LNG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,OUTDT_INF_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,DCSN_TAK_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,NTY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,SALUT_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IDENTN_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,IDENTN_NO		VARCHAR2(60)			
   ,DOC_ISSU_CITY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,DOC_ISSU_DT		DATE			
   ,DOC_ST_ID		NUMBER(9,0)		 DEFAULT -2	
   ,DOC_ISSU_CITY_NM		VARCHAR2(80)			
   ,DOC_ISSU_CTY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,RL_CMRCL_DSC		VARCHAR2(256)			
   ,IDENTN_NO_EXT		VARCHAR2(60)		 DEFAULT NULL	
);
/


CREATE TABLE DMRPMCOR.IP_X_IP_RLTNP(
    SBJ_IP_ID		NUMBER(9,0)			NOT NULL
   ,OBJ_IP_ID		NUMBER(9,0)			NOT NULL
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,RANK		NUMBER(5,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,PCT_AMT		NUMBER(10,7)			
   ,END_DT		DATE			
   ,DSC		VARCHAR2(256)			
   ,POS_ID		NUMBER(9,0)		 DEFAULT -2	
   ,AREA_MGT_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CTC_RSK_PRFL		VARCHAR2(2)			
   ,FNC_IMT_AHR_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CTC_TP_ID		NUMBER(9,0)		 DEFAULT -2	
);
/


CREATE TABLE DMRPMCOR.IP_X_LO_RLTNP(
    IP_ID		NUMBER(9,0)			NOT NULL
   ,LO_ID		NUMBER(9,0)			NOT NULL
   ,IP_X_LO_RLTNP_TP_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,RANK		NUMBER(5,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,END_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.IP_X_SRC_STM_RLTNP(
    IP_ID		NUMBER(9,0)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)			NOT NULL
   ,OU_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(30)			NOT NULL
   ,END_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.IP_X_TX_TP_RLTNP(
    TX_TP_ID		NUMBER(9,0)			NOT NULL
   ,IP_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,RANK		NUMBER(5,0)			NOT NULL
   ,TX_NOTE		VARCHAR2(4000)			
   ,END_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.LO(
    LO_ID		NUMBER(9,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(50)			NOT NULL
   ,LO_TP_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,PRN_LO_ID		NUMBER(9,0)		 DEFAULT -2	
   ,LO_NM		VARCHAR2(80)			
   ,LO_SHRT_NM		VARCHAR2(18)			
   ,EFF_DT		DATE			
   ,END_DT		DATE			
   ,SCDY_CODE		VARCHAR2(20)			
   ,TRCY_CODE		VARCHAR2(20)			
);
/


CREATE TABLE DMRPMCOR.LO_X_CL_RLTNP(
    LO_ID		NUMBER(9,0)			NOT NULL
   ,LO_X_CL_RLTNP_TP_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,RANK		NUMBER(5,0)			NOT NULL
   ,CV_ID		NUMBER(9,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,END_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.LO_X_LO_RLTNP(
    SBJ_LO_ID		NUMBER(9,0)			NOT NULL
   ,OBJ_LO_ID		NUMBER(9,0)			NOT NULL
   ,LO_X_LO_RLTNP_TP_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,RANK		NUMBER(5,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,END_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.LO_X_SRC_STM_RLTNP(
    SCDY_CODE		VARCHAR2(20)			NOT NULL
   ,OU_ID		NUMBER(9,0)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)			NOT NULL
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(30)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,END_DT		DATE			
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
);
/


CREATE TABLE DMRPMCOR.MSR_PRD(
    MSR_PRD_ID		NUMBER(9,0)			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)		 DEFAULT -2	
   ,UNQ_ID_IN_SRC_STM_ID		VARCHAR2(30)			
   ,TM_PRD_TP_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,EFF_DT		DATE			
   ,END_DT		DATE			
   ,MSR_PRD_NM		VARCHAR2(40)			
   ,CDR_YR		NUMBER(5,0)			
   ,CDR_QTR		NUMBER(5,0)			
   ,CDR_MO		NUMBER(5,0)			
   ,WK_OF_CDR_YR		NUMBER(5,0)			
   ,DAY_OF_CDR_YR		NUMBER(5,0)			
   ,DAY_CDR_MO		NUMBER(5,0)			
   ,DAY_OF_WK		NUMBER(5,0)			
   ,PBLC_HOL_F		NUMBER(5,0)			
   ,LAST_BSN_DAY_MO_F		NUMBER(5,0)			
   ,DSC		VARCHAR2(256)			
   ,FRN_OF_CDR_YR		NUMBER(5,0)			
);
/


CREATE TABLE DMRPMCOR.ORG(
    ORG_ID		NUMBER(9,0)			NOT NULL
   ,ORG_ECN_ITN_ID		NUMBER(9,0)		 DEFAULT -2	
   ,ORG_PPS_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,INC_ORG_GEO_ID		NUMBER(9,0)			
   ,INC_ORG_GEO_DT		DATE			
   ,UNQ_MCH_CODE		VARCHAR2(20)			
   ,UNQ_MCH_CODE_DT		DATE			
   ,ESTB_DT		DATE			
   ,ORG_TAX_ID_NO		VARCHAR2(60)			
   ,PRIM_CMRCL_NM		VARCHAR2(80)			
   ,RGST_BSN_NM		VARCHAR2(80)			
   ,ORG_DSLV_F		VARCHAR2(2)			
   ,ORG_LAW_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,ORG_CRPT_PRN_ID		NUMBER(9,0)		 DEFAULT -2	
   ,PPN_DT		DATE		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,PPN_TM		TIMESTAMP(6)		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,EFF_DT		DATE		 DEFAULT TO_DATE ('00010102', 'YYYYMMDD') 	NOT NULL
);
/


CREATE TABLE DMRPMCOR.ORG_PRFL(
    ORG_ID		NUMBER(9,0)			NOT NULL
   ,DNMN_CCY_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)			NOT NULL
   ,TOT_EQTY		NUMBER(24,4)			
   ,END_DT		DATE			
   ,MAIN_MO_INCM		NUMBER(24,4)			
   ,OTHR_MO_INCM		NUMBER(24,4)			
   ,OTHR_MO_INCM_DSC		VARCHAR2(256)			
   ,TOT_MO_INCM		NUMBER(24,4)			
   ,TOT_MO_EXPND		NUMBER(24,4)			
   ,TOT_AST		NUMBER(24,4)			
   ,TOT_LBY		NUMBER(24,4)			
   ,ANUL_SALE_DT		DATE			
   ,ANUL_SALE_VOL		NUMBER(24,4)			
   ,NUM_OF_PRJ		NUMBER(5,0)			
   ,MKT_SZ		NUMBER(24,4)			
   ,EMP_CNT		NUMBER(9,0)			
   ,NET_WHRT		NUMBER(24,4)			
   ,NET_INCM		NUMBER(24,4)			
);
/


CREATE TABLE DMRPMCOR.OU(
    OU_ID		NUMBER(9,0)			NOT NULL
   ,PRN_OU_IP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,ORG_ID		NUMBER(9,0)		 DEFAULT -2	
   ,OU_LCS_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,LOB_ID		NUMBER(9,0)		 DEFAULT -2	
   ,BR_NO		VARCHAR2(20)			
   ,OU_CODE		VARCHAR2(20)			
   ,OU_FCN_TP_ID		NUMBER(9,0)		 DEFAULT -2	
   ,OU_STC_TP_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,GEN_NO		NUMBER(5,0)			
);
/


CREATE TABLE DMRPMCOR.PRDC_ITRV(
    PRDC_ITRV_ID		NUMBER(9,0)			NOT NULL
   ,NBR_UNIT		NUMBER(5,0)			
   ,UOM_ID		NUMBER(9,0)		 DEFAULT -2	
);
/


CREATE TABLE DMRPMCOR.PST_ADR(
    PST_ADR_ID		NUMBER(9,0)			NOT NULL
   ,COMPL_ADR		VARCHAR2(256)			
   ,DSTC		VARCHAR2(80)			
   ,CITY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CITY_NM		VARCHAR2(80)			
   ,STE_ID		NUMBER(9,0)		 DEFAULT -2	
   ,CTY_ID		NUMBER(9,0)		 DEFAULT -2	
   ,BLD_NO		VARCHAR2(10)			
   ,STR_NO		VARCHAR2(3)			
   ,STR_NM		VARCHAR2(30)			
   ,PST_CODE		VARCHAR2(20)			
   ,BOX_NO		VARCHAR2(6)			
   ,PPN_DT		DATE		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,PPN_TM		TIMESTAMP(6)		 DEFAULT TO_DATE('02-01-0001', 'DD-MM-YYYY') 	NOT NULL
   ,EFF_DT		DATE		 DEFAULT TO_DATE ('00010102', 'YYYYMMDD') 	NOT NULL
   ,MARK_F		VARCHAR2(1)			
);
/


CREATE TABLE DMRPMCOR.RATE(
    RATE_ID		NUMBER(9,0)			NOT NULL
   ,RATE_TP_ID		NUMBER(9,0)		 DEFAULT -2 	NOT NULL
   ,REFR_RATE_ID		NUMBER(9,0)		 DEFAULT -2	
   ,RATE_NM		VARCHAR2(40)			
);
/


CREATE TABLE DMRPMCOR.SRC_STM(
    SRC_STM_ID		NUMBER(9,0)			NOT NULL
   ,SRC_STM_NM		VARCHAR2(80)			
   ,SRC_STM_CODE		VARCHAR2(20)			
   ,EFF_DT		DATE			
   ,END_DT		DATE			
   ,SRC_STM_DSC		VARCHAR2(256)			
);
/


CREATE TABLE DMRPMCOR.STM_VAR(
    STM_VAR_ID		NUMBER(9,0)			NOT NULL
   ,VAR_NM		VARCHAR2(80)			NOT NULL
   ,SVC_NM		VARCHAR2(256)			NOT NULL
   ,VAL		VARCHAR2(4000)			
   ,DSC		VARCHAR2(256)			
   ,EFF_DT		DATE			NOT NULL
   ,END_DT		DATE			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		TIMESTAMP(6)			NOT NULL
);
/


CREATE TABLE DMRPMCOR.TMP_CST_FRGN_CCY_OPRN(
    CSTMR_ID		NUMBER(10,0)			NOT NULL
   ,FRGN_CCY_PD_TP_ID		NUMBER(10,0)			NOT NULL
   ,OPRN_FRGN_CCY_TP_ID		NUMBER(10,0)			NOT NULL
   ,CITY_ID		NUMBER(10,0)			
   ,CTY_ID		NUMBER(10,0)			
   ,FRGN_CCY_ID		NUMBER(10,0)			
   ,OPRN_FRGN_CCY_F_ID		NUMBER(10,0)			
   ,OPERACION		NVARCHAR2(128)			
   ,FRGN_CCY_AC_NUM		NVARCHAR2(40)			NOT NULL
   ,OPRN_FRGN_CCY_BNK_NM		NVARCHAR2(120)			
   ,CITY_NM		NVARCHAR2(160)			
   ,FRGN_CCY_AV_AMT		NUMBER(24,4)			
   ,END_DT		DATE			
   ,EFF_DT		DATE			
);
/


CREATE TABLE DMRPMCOR.TMP_CSTMR(
    CSTMR_LCS_TP_ID		NUMBER(9,0)			
   ,CST_LCS_DT		DATE			
   ,CST_CGY_ID		NUMBER(9,0)			
   ,CST_CGY_DT		DATE			
   ,PRIM_BR_NO		NVARCHAR2(40)			
   ,PRIM_BR_ID		NUMBER(9,0)			
   ,RLN_EP_DT		DATE			
   ,EFF_CST_DT		DATE			
   ,END_CST_DT		DATE			
   ,GEO_AREA_ID		NUMBER(9,0)			
   ,CSTMR_MKT_SEG_ID		NUMBER(9,0)			
   ,CTC_CNL_ID		NUMBER(9,0)			
   ,CTC_LO_TP_ID		NUMBER(9,0)			
   ,CTC_DT		DATE			
   ,CTC_TM		DATE			
   ,FND_ORIG_CTY_ID		NUMBER(9,0)			
   ,FND_ORIG_CITY_ID		NUMBER(9,0)			
   ,FND_ORIG_CITY_NM		NVARCHAR2(160)			
   ,CSTMR_MKT_SUB_SEG_ID		NUMBER(9,0)			
   ,AC_STMT_DLV_TP_ID		NUMBER(9,0)			
   ,EMAIL_ADR_CTC_AHR_ID		NUMBER(9,0)			
   ,SMS_CTC_AHR_ID		NUMBER(9,0)			
   ,FRGN_EXG_BKR_ID		NUMBER(9,0)			
   ,FND_ORIG_ID		NUMBER(9,0)			
   ,PTY_ORIG_ID		NUMBER(9,0)			
   ,CST_RLTNP_ST_ID		NUMBER(9,0)			
   ,BLC_F		NVARCHAR2(4)			
   ,CST_RLTNP_AVY_ST_ID		NUMBER(9,0)			
   ,CITY_FILN_ID		NUMBER(9,0)			
   ,CITY_FILN_NM		NVARCHAR2(160)			
   ,CST_SPCL_PRGM_TP_ID		NUMBER(9,0)			
   ,EXMPT_CASH_OPRN_STMT_ID		NUMBER(9,0)			
   ,FNC_IMT_PD_F_ID		NUMBER(9,0)			
   ,CHKLST_VLD_DT		DATE			
   ,INTVN_LAW_TP_ID		NUMBER(9,0)			
   ,SPCL_CR_ADMN_TP_ID		NUMBER(9,0)			
   ,PCRMT_PCS_CL_TP_ID		NUMBER(9,0)			
   ,CST_EMP_EXN_TP_ID		NUMBER(9,0)			
   ,MAIN_EMAIL_ADR		NVARCHAR2(482)			
   ,MAIN_WEBST_ADR		NVARCHAR2(2000)			
   ,CST_PTNL_VAL_TP_ID		NUMBER(9,0)			
   ,CST_STRTG_VAL_TP_ID		NUMBER(9,0)			
   ,PAM_CODE		NVARCHAR2(40)			
   ,UDT_DOC_FILLN_DT		DATE			
   ,EFF_LKG_DT		DATE			
   ,UDT_CNL_ID		NUMBER(9,0)			
   ,RET_AC_STMT_TP_ID		NUMBER(9,0)			
   ,AST_MGT_F		NVARCHAR2(4)			
   ,PRVT_SEG_F		NVARCHAR2(4)			
   ,SOC_STL_TP_ID		NUMBER(9,0)			
   ,PBLC_EXD_ID		NUMBER(9,0)			
   ,PBLC_EXD_FE_ID		NUMBER(9,0)			
   ,EFF_LKG_DT_FE		DATE			
   ,CSTMR_RTF_WHLD_TP_ID		NUMBER(9,0)			
   ,CSTMR_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			
   ,PPN_DT		DATE			
   ,PPN_TM		TIMESTAMP(6)			
   ,CLAVE_CSTMR		CHAR(1)			
);
/


CREATE TABLE DMRPMCOR.TMP_ELC_ADR(
    EXN		VARCHAR2(10)			
   ,FULL_TEL_NO		VARCHAR2(30)			
   ,URL		VARCHAR2(2048)			
   ,EMAIL_ADR		VARCHAR2(241)			
   ,ELC_ADR_ID		NUMBER(9,0)			NOT NULL
   ,ELC_ADR_TP_ID		NUMBER(9,0)			
   ,TEL_DVC_TP_ID		NUMBER(9,0)			
   ,EFF_DT		DATE			
   ,PPN_DT		DATE			
   ,PPN_TM		TIMESTAMP(6)			
   ,CLAVE_ELC_ADR		CHAR(1)			
);
/


CREATE TABLE DMRPMCOR.TMP_IDV(
    IDV_ID		NUMBER(9,0)			NOT NULL
   ,GND_ID		NUMBER(9,0)			
   ,BRTH_DT		DATE			
   ,IDV_MAR_ST_TP_ID		NUMBER(9,0)			
   ,CTF_TP_ID		NUMBER(9,0)			
   ,IDV_OCP_TP_ID		NUMBER(9,0)			
   ,CTY_BRTH_ID		NUMBER(9,0)			
   ,GVN_NM		NVARCHAR2(80)			
   ,MDL_NM		NVARCHAR2(80)			
   ,SURNM1		NVARCHAR2(80)			
   ,SURNM2		NVARCHAR2(80)			
   ,FULL_NM		NVARCHAR2(512)			
   ,CITY_BRTH_ID		NUMBER(9,0)			
   ,EMPR_NM		NVARCHAR2(80)			
   ,DEATH_ST_ID		NUMBER(9,0)			
   ,KNPD_F		NVARCHAR2(4)			
   ,SBN_CODE		NVARCHAR2(40)			
   ,EXL_RGSTY		NVARCHAR2(60)			
   ,HOB		NVARCHAR2(128)			
   ,SPRT		NVARCHAR2(128)			
   ,MNOR_F		NVARCHAR2(4)			
   ,CTY_BRTH_NM		NVARCHAR2(160)			
   ,UCPBL_TP_ID		NUMBER(9,0)			
   ,SOCIO_ECN_CGY_ID		NUMBER(9,0)			
   ,IDV_IDY_CL_ID		NUMBER(9,0)			
   ,IDV_EMP_ST_TP_ID		NUMBER(9,0)			
   ,IDV_HLT_ST_TP_ID		NUMBER(9,0)			
   ,NM_INL		NVARCHAR2(12)			
   ,EFF_DT		DATE			
   ,PPN_DT		DATE			
   ,PPN_TM		TIMESTAMP(6)			
   ,CLAVE_IDV		CHAR(1)			
);
/


CREATE TABLE DMRPMCOR.TMP_IDV_PRFL(
    IDV_ID		NUMBER(9,0)			NOT NULL
   ,DNMN_CCY_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		DATE			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)			NOT NULL
   ,END_DT		DATE			NOT NULL
   ,MAIN_MO_INCM		NUMBER(24,4)			
   ,OTHR_MO_INCM		NUMBER(24,4)			
   ,TOT_MO_INCM		NUMBER(24,4)			
   ,TOT_MO_EXPND		NUMBER(24,4)			
   ,TOT_AST		NUMBER(24,4)			
   ,TOT_LBY		NUMBER(24,4)			
   ,TOT_EQTY		NUMBER(24,4)			
   ,ANUL_SALE_DT		DATE			
   ,ANUL_SALE_VOL		NUMBER(24,4)			
   ,MKT_SZ		NUMBER(24,4)			
   ,NBR_DPND_CHL		NUMBER(5,0)			
   ,EMP_CNT		NUMBER(9,0)			
   ,CLAVE_IDV_PRFL		CHAR(1)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP(
    IP_ID		NUMBER(10,0)			NOT NULL
   ,SRC_STM_ID		NUMBER(10,0)			NOT NULL
   ,UNQ_ID_IN_SRC_STM_ID		NVARCHAR2(60)			NOT NULL
   ,TIPOACTUALIZACION		VARCHAR2(1)			NOT NULL
   ,EFF_DT		DATE			
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		DATE			NOT NULL
   ,IP_TP_ID		NUMBER(10,0)			NOT NULL
   ,PRIM_RLN_TP_ID		NUMBER(10,0)			
   ,IP_NM		NVARCHAR2(160)			
   ,SHRT_NM		NVARCHAR2(80)			
   ,FI_F		NUMBER(10,0)			
   ,END_DT		DATE			
   ,DSC		NVARCHAR2(512)			
   ,COL_RSDNT_ID		NUMBER(10,0)			
   ,BSN_SECT_ID		NUMBER(10,0)			
   ,BSN_SUB_SECT_ID		NUMBER(10,0)			
   ,ECN_AVY_ID		NUMBER(10,0)			
   ,CIIU_IDY_CL_ID		NUMBER(10,0)			
   ,SUB_CIIU_IDY_CL_ID		NUMBER(10,0)			
   ,BLCKLIST_ACTN_ID		NUMBER(10,0)			
   ,DOC_VLD_RSP_ID		NUMBER(10,0)			
   ,VIN_RSK_FCTR_ID		NUMBER(10,0)			
   ,REG_INST_MOND_ID		NUMBER(10,0)			
   ,ORG_ENT_TP_ID		NUMBER(10,0)			
   ,DCNT_STE_ENT_TP_ID		NUMBER(10,0)			
   ,STE_ENT_TP_ID		NUMBER(10,0)			
   ,IP_TAX_RPT_ID		NUMBER(10,0)			
   ,TAX_SLF_WHLD_ID		NUMBER(10,0)			
   ,TPY_CLSS_ID		NUMBER(10,0)			
   ,TPY_TP_ID		NUMBER(10,0)			
   ,IVA_RSPL_TP_ID		NUMBER(10,0)			
   ,IVA_RGM_TP_ID		NUMBER(10,0)			
   ,WHLD_TP_ID		NUMBER(10,0)			
   ,NON_CMRCL_RLV_F		NVARCHAR2(4)			
   ,PREF_CTC_MTH_ID		NUMBER(10,0)			
   ,PRIM_RLN_TP_DT		DATE			
   ,INR_IP_CR_RSK_RTG_ID		NUMBER(10,0)			
   ,LAST_UDT_DT		DATE			
   ,IP_GRP_TP_ID		NUMBER(10,0)			
   ,COM_ATTD_TP_ID		NUMBER(10,0)			
   ,LNG_ID		NUMBER(10,0)			
   ,OUTDT_INF_TP_ID		NUMBER(10,0)			
   ,DCSN_TAK_TP_ID		NUMBER(10,0)			
   ,NTY_ID		NUMBER(10,0)			
   ,IDENTN_TP_ID		NUMBER(10,0)			
   ,IDENTN_NO		NVARCHAR2(120)			
   ,DOC_ISSU_CITY_ID		NUMBER(10,0)			
   ,DOC_ISSU_DT		DATE			
   ,DOC_ST_ID		NUMBER(10,0)			
   ,DOC_ISSU_CITY_NM		NVARCHAR2(160)			
   ,DOC_ISSU_CTY_ID		NUMBER(10,0)			
   ,SALUT_TP_ID		NUMBER(10,0)			
   ,IDENTN_NO_EXT		VARCHAR2(60)		 DEFAULT NULL	
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP(
    PPN_DT		DATE			
   ,PPN_TM		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
   ,SRC_STM_ID		NUMBER(9,0)			
   ,POS_ID		NUMBER(9,0)			
   ,AREA_MGT_TP_ID		NUMBER(9,0)			
   ,CTC_RSK_PRFL		NVARCHAR2(4)			
   ,FNC_IMT_AHR_TP_ID		NUMBER(9,0)			
   ,PCT_AMT		NUMBER(11,7)			
   ,END_DT		DATE			
   ,DSC		NVARCHAR2(512)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP1_DRP(
    EFF_DT		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP2(
    PPN_DT		DATE			
   ,PPN_TM		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
   ,SRC_STM_ID		NUMBER(9,0)			
   ,END_DT		DATE			
   ,POS_ID		NUMBER(9,0)			
   ,AREA_MGT_TP_ID		NUMBER(9,0)			
   ,PCT_AMT		NUMBER(10,7)			
   ,DSC		NVARCHAR2(512)			
   ,CTC_RSK_PRFL		NVARCHAR2(4)			
   ,FNC_IMT_AHR_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP2_DRP(
    EFF_DT		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP3(
    PPN_DT		DATE			
   ,PPN_TM		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
   ,SRC_STM_ID		NUMBER(9,0)			
   ,END_DT		DATE			
   ,POS_ID		NUMBER(9,0)			
   ,AREA_MGT_TP_ID		NUMBER(9,0)			
   ,PCT_AMT		NUMBER(10,7)			
   ,DSC		NVARCHAR2(512)			
   ,CTC_RSK_PRFL		NVARCHAR2(4)			
   ,FNC_IMT_AHR_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP3_DRP(
    EFF_DT		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP4(
    PPN_DT		DATE			
   ,PPN_TM		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
   ,SRC_STM_ID		NUMBER(9,0)			
   ,END_DT		DATE			
   ,POS_ID		NUMBER(9,0)			
   ,AREA_MGT_TP_ID		NUMBER(9,0)			
   ,PCT_AMT		NUMBER(10,7)			
   ,DSC		NVARCHAR2(512)			
   ,CTC_RSK_PRFL		NVARCHAR2(4)			
   ,FNC_IMT_AHR_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP4_DRP(
    EFF_DT		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP5(
    PPN_DT		DATE			
   ,PPN_TM		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
   ,SRC_STM_ID		NUMBER(9,0)			
   ,PCT_AMT		NUMBER(10,7)			
   ,END_DT		DATE			
   ,DSC		NVARCHAR2(512)			
   ,POS_ID		NUMBER(9,0)			
   ,AREA_MGT_TP_ID		NUMBER(9,0)			
   ,CTC_RSK_PRFL		NVARCHAR2(4)			
   ,FNC_IMT_AHR_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP5_DRP(
    EFF_DT		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP6(
    PPN_DT		DATE			
   ,PPN_TM		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
   ,SRC_STM_ID		NUMBER(9,0)			
   ,END_DT		DATE			
   ,POS_ID		NUMBER(9,0)			
   ,AREA_MGT_TP_ID		NUMBER(9,0)			
   ,PCT_AMT		NUMBER(10,7)			
   ,DSC		NVARCHAR2(512)			
   ,CTC_RSK_PRFL		NVARCHAR2(4)			
   ,FNC_IMT_AHR_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_IP_RLTNP6_DRP(
    EFF_DT		DATE			
   ,SBJ_IP_ID		NUMBER(9,0)			
   ,OBJ_IP_ID		NUMBER(9,0)			
   ,IP_X_IP_RLTNP_TP_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_IP_X_LO_RLTNP(
    IP_ID		NUMBER(9,0)			
   ,IP_X_LO_RLTNP_TP_ID		NUMBER(9,0)			
   ,PPN_DT		DATE			
   ,PPN_TM		DATE			
   ,SRC_STM_ID		NUMBER(9,0)			
   ,END_DT		DATE			
   ,LO_ID		NUMBER(9,0)			
);
/


CREATE TABLE DMRPMCOR.TMP_LO(
    PPN_DT		DATE			
   ,PPN_TM		DATE			
   ,END_DT		DATE			
   ,LO_ID		NUMBER(9,0)			
   ,TRCY_CODE		VARCHAR2(20)			
);
/


CREATE TABLE DMRPMCOR.TMP_LO_ADR(
    EFF_DT		DATE			
   ,END_DT		DATE			
   ,LO_ID		NUMBER(10,0)			NOT NULL
);
/


CREATE TABLE DMRPMCOR.TMP_ORG(
    ORG_ID		NUMBER(9,0)			NOT NULL
   ,ORG_ECN_ITN_ID		NUMBER(9,0)			
   ,ORG_PPS_TP_ID		NUMBER(9,0)			
   ,INC_ORG_GEO_ID		NUMBER(9,0)			
   ,INC_ORG_GEO_DT		DATE			
   ,ESTB_DT		DATE			
   ,ORG_TAX_ID_NO		NVARCHAR2(120)			
   ,PRIM_CMRCL_NM		NVARCHAR2(160)			
   ,RGST_BSN_NM		NVARCHAR2(160)			
   ,ORG_DSLV_F		NVARCHAR2(4)			
   ,ORG_LAW_TP_ID		NUMBER(9,0)			
   ,ORG_CRPT_PRN_ID		NUMBER(9,0)			
   ,PPN_DT		DATE			
   ,PPN_TM		TIMESTAMP(6)			
   ,EFF_DT		DATE			
   ,CLAVE_ORG		CHAR(1)			
);
/


CREATE TABLE DMRPMCOR.TMP_ORG_PRFL(
    ORG_ID		NUMBER(9,0)			NOT NULL
   ,DNMN_CCY_ID		NUMBER(9,0)			NOT NULL
   ,EFF_DT		DATE			NOT NULL
   ,PPN_DT		DATE			NOT NULL
   ,PPN_TM		DATE			NOT NULL
   ,SRC_STM_ID		NUMBER(9,0)			NOT NULL
   ,TOT_EQTY		NUMBER(24,4)			
   ,END_DT		DATE			NOT NULL
   ,MAIN_MO_INCM		NUMBER(24,4)			
   ,OTHR_MO_INCM		NUMBER(24,4)			
   ,OTHR_MO_INCM_DSC		NVARCHAR2(512)			
   ,TOT_MO_INCM		NUMBER(24,4)			
   ,TOT_MO_EXPND		NUMBER(24,4)			
   ,TOT_AST		NUMBER(24,4)			
   ,TOT_LBY		NUMBER(24,4)			
   ,ANUL_SALE_DT		DATE			
   ,ANUL_SALE_VOL		NUMBER(24,4)			
   ,NUM_OF_PRJ		NUMBER(5,0)			
   ,MKT_SZ		NUMBER(24,4)			
   ,EMP_CNT		NUMBER(9,0)			
   ,CLAVE_ORG_PRFL		CHAR(1)			
);
/


CREATE TABLE DMRPMCOR.TMP_PST_ADR(
    PST_ADR_ID		NUMBER(9,0)			NOT NULL
   ,COMPL_ADR		NVARCHAR2(512)			
   ,DSTC		NVARCHAR2(160)			
   ,CITY_ID		NUMBER(9,0)			NOT NULL
   ,CITY_NM		NVARCHAR2(160)			
   ,STE_ID		NUMBER(9,0)			NOT NULL
   ,CTY_ID		NUMBER(9,0)			NOT NULL
   ,BLD_NO		NVARCHAR2(20)			
   ,STR_NO		NVARCHAR2(6)			
   ,STR_NM		NVARCHAR2(60)			
   ,PST_CODE		NVARCHAR2(40)			
   ,BOX_NO		NVARCHAR2(12)			
   ,MARK_F		NVARCHAR2(2)			
   ,EFF_DT		DATE			
   ,PPN_DT		DATE			
   ,PPN_TM		TIMESTAMP(6)			
   ,CLAVE_PST_ADR		CHAR(1)			
);
/

CREATE UNIQUE INDEX DMRPMCOR.CD_PK ON DMRPMCOR.CD (CNDTN_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.CNL_PK ON DMRPMCOR.CNL (CNL_ID ASC);
CREATE  INDEX DMRPMCOR.IDV__IDX ON DMRPMCOR.IDV (IDV_ID ASC);
CREATE  INDEX DMRPMCOR.LO_IDX_3 ON DMRPMCOR.LO (SCDY_CODE ASC,LO_ID ASC);
CREATE  INDEX DMRPMCOR.ORG__IDX ON DMRPMCOR.ORG (ORG_ID ASC);
CREATE  INDEX DMRPMCOR.IP__IDX_1 ON DMRPMCOR.IP (IP_ID ASC);
CREATE  INDEX DMRPMCOR.IP__IDX_2 ON DMRPMCOR.IP (SRC_STM_ID ASC,UNQ_ID_IN_SRC_STM_ID ASC);
CREATE  INDEX DMRPMCOR.IP__IDX_3 ON DMRPMCOR.IP (IP_TP_ID ASC);
CREATE  INDEX DMRPMCOR.IP__IDX_4 ON DMRPMCOR.IP (IDENTN_TP_ID ASC,IDENTN_NO ASC);
CREATE  INDEX DMRPMCOR.IP__IDX_5 ON DMRPMCOR.IP (UNQ_ID_IN_SRC_STM_ID ASC);
CREATE  INDEX DMRPMCOR.LO__IDX_1 ON DMRPMCOR.LO (LO_ID ASC);
CREATE  INDEX DMRPMCOR.LO__IDX_2 ON DMRPMCOR.LO (UNQ_ID_IN_SRC_STM_ID ASC,LO_TP_ID ASC);
CREATE  INDEX DMRPMCOR.OU__IDX_1 ON DMRPMCOR.OU (OU_ID ASC);
CREATE  INDEX DMRPMCOR.OU__IDX_2 ON DMRPMCOR.OU (OU_CODE ASC);
CREATE  INDEX DMRPMCOR.CNL__IDX_2 ON DMRPMCOR.CNL (UNQ_ID_IN_SRC_STM_ID ASC);
CREATE  INDEX DMRPMCOR.CNL__IDX_3 ON DMRPMCOR.CNL (CNL_TP_ID ASC);
CREATE  INDEX DMRPMCOR.CSTMR__IDX ON DMRPMCOR.CSTMR (CSTMR_ID ASC);
CREATE  INDEX DMRPMCOR.EMP__IDX_1 ON DMRPMCOR.EMP (EMP_ID ASC);
CREATE  INDEX DMRPMCOR.EMP__IDX_2 ON DMRPMCOR.EMP (EMPE_NO ASC);
CREATE UNIQUE INDEX DMRPMCOR.EMP__IDX_3 ON DMRPMCOR.EMP (UNQ_ID_IN_SRC_STM_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.STM_VAR_PK ON DMRPMCOR.STM_VAR (STM_VAR_ID ASC);
CREATE  INDEX DMRPMCOR.ELC_ADR__IDX ON DMRPMCOR.ELC_ADR (ELC_ADR_ID ASC);
CREATE  INDEX DMRPMCOR.PST_ADR__IDX ON DMRPMCOR.PST_ADR (PST_ADR_ID ASC);
CREATE  INDEX DMRPMCOR.CL_SCM__IDX_1 ON DMRPMCOR.CL_SCM (CL_SCM_ID ASC);
CREATE  INDEX DMRPMCOR.CL_SCM__IDX_2 ON DMRPMCOR.CL_SCM (SCM_CODE ASC);
CREATE  INDEX DMRPMCOR.CL_TSL__IDX_1 ON DMRPMCOR.CL_TSL (CL_TSL_ID ASC,LNG_ID ASC);
CREATE  INDEX DMRPMCOR.CL_VAL__IDX_2 ON DMRPMCOR.CL_VAL (CL_VAL_ID ASC,UNQ_ID_IN_SRC_STM_ID ASC);
CREATE  INDEX DMRPMCOR.CL_VAL__IDX_3 ON DMRPMCOR.CL_VAL (CL_CD ASC);
CREATE  INDEX DMRPMCOR.IDV_PRFL__IDX ON DMRPMCOR.IDV_PRFL (IDV_ID ASC);
CREATE  INDEX DMRPMCOR.ORG_PRFL__IDX ON DMRPMCOR.ORG_PRFL (ORG_ID ASC);
CREATE  INDEX DMRPMCOR.SRC_STM_IDX_2 ON DMRPMCOR.SRC_STM (SRC_STM_CODE ASC,SRC_STM_ID ASC);
CREATE  INDEX DMRPMCOR.SRC_STM_IDX_3 ON DMRPMCOR.SRC_STM (SRC_STM_CODE ASC,END_DT ASC);
CREATE  INDEX DMRPMCOR.SRC_STM__IDX_1 ON DMRPMCOR.SRC_STM (SRC_STM_ID ASC);
CREATE  INDEX DMRPMCOR.CD_CNDTN_ID_IDX ON DMRPMCOR.CD (UNQ_ID_IN_SRC_STM_ID ASC,CNDTN_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.CL_X_CL_RLTNP_PK ON DMRPMCOR.CL_X_CL_RLTNP (SBJ_CL_ID ASC,OBJ_CL_ID ASC,CL_X_CL_RLTNP_TP_ID ASC,EFF_DT ASC,RANK ASC);
CREATE UNIQUE INDEX DMRPMCOR.CL_X_IP_RLTNP_PK ON DMRPMCOR.CL_X_IP_RLTNP (CV_ID ASC,IP_ID ASC,CL_X_IP_RLTNP_TP_ID ASC,EFF_DT ASC,RANK ASC);
CREATE UNIQUE INDEX DMRPMCOR.IP_X_IP_RLTNP_PK ON DMRPMCOR.IP_X_IP_RLTNP (SBJ_IP_ID ASC,OBJ_IP_ID ASC,IP_X_IP_RLTNP_TP_ID ASC,EFF_DT ASC,RANK ASC);
CREATE  INDEX DMRPMCOR.IP_X_LO_RLTNP_LO ON DMRPMCOR.IP_X_LO_RLTNP (LO_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.IP_X_LO_RLTNP_PK ON DMRPMCOR.IP_X_LO_RLTNP (IP_ID ASC,LO_ID ASC,IP_X_LO_RLTNP_TP_ID ASC,EFF_DT ASC,RANK ASC);
CREATE UNIQUE INDEX DMRPMCOR.LO_X_CL_RLTNP_PK ON DMRPMCOR.LO_X_CL_RLTNP (LO_ID ASC,LO_X_CL_RLTNP_TP_ID ASC,EFF_DT ASC,RANK ASC,CV_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.LO_X_LO_RLTNP_PK ON DMRPMCOR.LO_X_LO_RLTNP (SBJ_LO_ID ASC,OBJ_LO_ID ASC,LO_X_LO_RLTNP_TP_ID ASC,EFF_DT ASC,RANK ASC);
CREATE UNIQUE INDEX DMRPMCOR.RATE_RATE_ID_IDX1 ON DMRPMCOR.RATE (RATE_ID ASC);
CREATE  INDEX DMRPMCOR.CL_X_CL_RLTNP__IDX ON DMRPMCOR.CL_X_CL_RLTNP (SBJ_CL_ID ASC,OBJ_CL_ID ASC,CL_X_CL_RLTNP_TP_ID ASC);
CREATE  INDEX DMRPMCOR.CL_X_IP_RLTNP__IDX ON DMRPMCOR.CL_X_IP_RLTNP (IP_ID ASC,CL_X_IP_RLTNP_TP_ID ASC,CV_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.CTY_X_CCY_RLTNP_PK ON DMRPMCOR.CTY_X_CCY_RLTNP (CCY_ID ASC,CTY_ID ASC,EFF_DT ASC);
CREATE  INDEX DMRPMCOR.IP_X_LO_RLTNP__IDX ON DMRPMCOR.IP_X_LO_RLTNP (IP_ID ASC,LO_ID ASC,IP_X_LO_RLTNP_TP_ID ASC);
CREATE  INDEX DMRPMCOR.LO_X_CL_RLTNP__IDX ON DMRPMCOR.LO_X_CL_RLTNP (LO_ID ASC,CV_ID ASC);
CREATE  INDEX DMRPMCOR.LO_X_LO_RLTNP__IDX ON DMRPMCOR.LO_X_LO_RLTNP (SBJ_LO_ID ASC,OBJ_LO_ID ASC,LO_X_LO_RLTNP_TP_ID ASC);
CREATE  INDEX DMRPMCOR.STM_VAR_VAR_NM_IDX ON DMRPMCOR.STM_VAR (VAR_NM ASC,SVC_NM ASC);
CREATE  INDEX DMRPMCOR.IP_X_IP_RLTNP_IDX_2 ON DMRPMCOR.IP_X_IP_RLTNP (SBJ_IP_ID ASC,RANK ASC,IP_X_IP_RLTNP_TP_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.IP_X_TX_TP_RLTNP_PK ON DMRPMCOR.IP_X_TX_TP_RLTNP (TX_TP_ID ASC,IP_ID ASC,EFF_DT ASC,RANK ASC);
CREATE  INDEX DMRPMCOR.CSTMR_OU_RLTNP_IDX_1 ON DMRPMCOR.CSTMR_X_OU_RLTNP (CSTMR_ID ASC,OU_ID ASC);
CREATE  INDEX DMRPMCOR.CSTMR_OU_RLTNP_IDX_2 ON DMRPMCOR.CSTMR_X_OU_RLTNP (CSTMR_X_OU_RLTNP_ID ASC);
CREATE  INDEX DMRPMCOR.CTY_X_CCY_RLTNP__IDX ON DMRPMCOR.CTY_X_CCY_RLTNP (CTY_ID ASC,CCY_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.IP_X_SRC_STM_RLTNP_PK ON DMRPMCOR.IP_X_SRC_STM_RLTNP (IP_ID ASC,SRC_STM_ID ASC,OU_ID ASC,EFF_DT ASC);
CREATE  INDEX DMRPMCOR.IP_X_TX_TP_RLTNP__IDX ON DMRPMCOR.IP_X_TX_TP_RLTNP (IP_ID ASC,TX_TP_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.LO_X_SRC_STM_RLTNP_PK ON DMRPMCOR.LO_X_SRC_STM_RLTNP (OU_ID ASC,SCDY_CODE ASC,SRC_STM_ID ASC);
CREATE  INDEX DMRPMCOR.CST_FRGN_CCY_OPRN__IDX ON DMRPMCOR.CST_FRGN_CCY_OPRN (CSTMR_ID ASC,OPRN_FRGN_CCY_TP_ID ASC,FRGN_CCY_AC_NUM ASC,FRGN_CCY_PD_TP_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.MSR_PRD_MSR_PRD_ID_IDX1 ON DMRPMCOR.MSR_PRD (MSR_PRD_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP_PK ON DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP (CSTMR_X_OU_RLTNP_ID ASC,CL_X_OU_X_CSTMR_RLTNP_TP_ID ASC);
CREATE  INDEX DMRPMCOR.IP_X_SRC_STM_RLTNP_IDX_4 ON DMRPMCOR.IP_X_SRC_STM_RLTNP (UNQ_ID_IN_SRC_STM_ID ASC,IP_ID ASC,SRC_STM_ID ASC,EFF_DT ASC,OU_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.EXG_RATE_EXG_RATE_ID_IDX1 ON DMRPMCOR.EXG_RATE (EXG_RATE_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.INT_RATE_INT_RATE_ID_IDX1 ON DMRPMCOR.INT_RATE (INT_RATE_ID ASC);
CREATE  INDEX DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP__IDX ON DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP (CSTMR_X_OU_RLTNP_ID ASC);
CREATE UNIQUE INDEX DMRPMCOR.PRDC_ITRV_PRDC_ITRV_ID_IDX1 ON DMRPMCOR.PRDC_ITRV (PRDC_ITRV_ID ASC);

ALTER TABLE DMRPMCOR.CD ADD CONSTRAINT CD_PK PRIMARY KEY ( CNDTN_ID ) USING INDEX DMRPMCOR.CD_PK;
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_PK PRIMARY KEY ( IP_ID ) USING INDEX DMRPMCOR.IP__IDX_1;
ALTER TABLE DMRPMCOR.LO ADD CONSTRAINT LO_PK PRIMARY KEY ( LO_ID ) USING INDEX DMRPMCOR.LO__IDX_1;
ALTER TABLE DMRPMCOR.OU ADD CONSTRAINT OU_PK PRIMARY KEY ( OU_ID ) USING INDEX DMRPMCOR.OU__IDX_1;
ALTER TABLE DMRPMCOR.CNL ADD CONSTRAINT CNL_PK PRIMARY KEY ( CNL_ID ) USING INDEX DMRPMCOR.CNL_PK;
ALTER TABLE DMRPMCOR.EMP ADD CONSTRAINT EMP_PK PRIMARY KEY ( EMP_ID ) USING INDEX DMRPMCOR.EMP__IDX_1;
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_PK PRIMARY KEY ( IDV_ID ) USING INDEX DMRPMCOR.IDV__IDX;
ALTER TABLE DMRPMCOR.ORG ADD CONSTRAINT ORG_PK PRIMARY KEY ( ORG_ID ) USING INDEX DMRPMCOR.ORG__IDX;
ALTER TABLE DMRPMCOR.RATE ADD CONSTRAINT RATE_PK PRIMARY KEY ( RATE_ID ) USING INDEX DMRPMCOR.RATE_RATE_ID_IDX1;
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_PK PRIMARY KEY ( CSTMR_ID ) USING INDEX DMRPMCOR.CSTMR__IDX;
ALTER TABLE DMRPMCOR.CL_SCM ADD CONSTRAINT CL_SCM_PK PRIMARY KEY ( CL_SCM_ID ) USING INDEX DMRPMCOR.CL_SCM__IDX_1;
ALTER TABLE DMRPMCOR.CL_TSL ADD CONSTRAINT CL_TSL_PK PRIMARY KEY ( CL_TSL_ID,LNG_ID ) USING INDEX DMRPMCOR.CL_TSL__IDX_1;
ALTER TABLE DMRPMCOR.CL_VAL ADD CONSTRAINT CL_VAL_PK PRIMARY KEY ( CL_VAL_ID ) USING INDEX DMRPMCOR.CL_VAL__IDX_2;
ALTER TABLE DMRPMCOR.ELC_ADR ADD CONSTRAINT ELC_ADR_PK PRIMARY KEY ( ELC_ADR_ID ) USING INDEX DMRPMCOR.ELC_ADR__IDX;
ALTER TABLE DMRPMCOR.MSR_PRD ADD CONSTRAINT MSR_PRD_PK PRIMARY KEY ( MSR_PRD_ID ) USING INDEX DMRPMCOR.MSR_PRD_MSR_PRD_ID_IDX1;
ALTER TABLE DMRPMCOR.PST_ADR ADD CONSTRAINT PST_ADR_PK PRIMARY KEY ( PST_ADR_ID ) USING INDEX DMRPMCOR.PST_ADR__IDX;
ALTER TABLE DMRPMCOR.SRC_STM ADD CONSTRAINT SRC_STM_PK PRIMARY KEY ( SRC_STM_ID ) USING INDEX DMRPMCOR.SRC_STM__IDX_1;
ALTER TABLE DMRPMCOR.STM_VAR ADD CONSTRAINT STM_VAR_PK PRIMARY KEY ( STM_VAR_ID ) USING INDEX DMRPMCOR.STM_VAR_PK;
ALTER TABLE DMRPMCOR.EXG_RATE ADD CONSTRAINT EXG_RATE_PK PRIMARY KEY ( EXG_RATE_ID ) USING INDEX DMRPMCOR.EXG_RATE_EXG_RATE_ID_IDX1;
ALTER TABLE DMRPMCOR.IDV_PRFL ADD CONSTRAINT IDV_PRFL_PK PRIMARY KEY ( IDV_ID ) USING INDEX DMRPMCOR.IDV_PRFL__IDX;
ALTER TABLE DMRPMCOR.INT_RATE ADD CONSTRAINT INT_RATE_PK PRIMARY KEY ( INT_RATE_ID ) USING INDEX DMRPMCOR.INT_RATE_INT_RATE_ID_IDX1;
ALTER TABLE DMRPMCOR.ORG_PRFL ADD CONSTRAINT ORG_PRFL_PK PRIMARY KEY ( ORG_ID ) USING INDEX DMRPMCOR.ORG_PRFL__IDX;
ALTER TABLE DMRPMCOR.PRDC_ITRV ADD CONSTRAINT PRDC_ITRV_PK PRIMARY KEY ( PRDC_ITRV_ID ) USING INDEX DMRPMCOR.PRDC_ITRV_PRDC_ITRV_ID_IDX1;
ALTER TABLE DMRPMCOR.CL_X_CL_RLTNP ADD CONSTRAINT CL_X_CL_RLTNP_PK PRIMARY KEY ( CL_X_CL_RLTNP_TP_ID,EFF_DT,OBJ_CL_ID,RANK,SBJ_CL_ID ) USING INDEX DMRPMCOR.CL_X_CL_RLTNP_PK;
ALTER TABLE DMRPMCOR.CL_X_IP_RLTNP ADD CONSTRAINT CL_X_IP_RLTNP_PK PRIMARY KEY ( CL_X_IP_RLTNP_TP_ID,CV_ID,EFF_DT,IP_ID,RANK ) USING INDEX DMRPMCOR.CL_X_IP_RLTNP_PK;
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT IP_X_IP_RLTNP_PK PRIMARY KEY ( EFF_DT,IP_X_IP_RLTNP_TP_ID,OBJ_IP_ID,RANK,SBJ_IP_ID ) USING INDEX DMRPMCOR.IP_X_IP_RLTNP_PK;
ALTER TABLE DMRPMCOR.IP_X_LO_RLTNP ADD CONSTRAINT IP_X_LO_RLTNP_PK PRIMARY KEY ( EFF_DT,IP_ID,IP_X_LO_RLTNP_TP_ID,LO_ID,RANK ) USING INDEX DMRPMCOR.IP_X_LO_RLTNP_PK;
ALTER TABLE DMRPMCOR.LO_X_CL_RLTNP ADD CONSTRAINT LO_X_CL_RLTNP_PK PRIMARY KEY ( CV_ID,EFF_DT,LO_ID,LO_X_CL_RLTNP_TP_ID,RANK ) USING INDEX DMRPMCOR.LO_X_CL_RLTNP_PK;
ALTER TABLE DMRPMCOR.LO_X_LO_RLTNP ADD CONSTRAINT LO_X_LO_RLTNP_PK PRIMARY KEY ( EFF_DT,LO_X_LO_RLTNP_TP_ID,OBJ_LO_ID,RANK,SBJ_LO_ID ) USING INDEX DMRPMCOR.LO_X_LO_RLTNP_PK;
ALTER TABLE DMRPMCOR.CTY_X_CCY_RLTNP ADD CONSTRAINT CTY_X_CCY_RLTNP_PK PRIMARY KEY ( CCY_ID,CTY_ID,EFF_DT ) USING INDEX DMRPMCOR.CTY_X_CCY_RLTNP_PK;
ALTER TABLE DMRPMCOR.CSTMR_X_OU_RLTNP ADD CONSTRAINT CSTMR_X_OU_RLTNP_PK PRIMARY KEY ( CSTMR_X_OU_RLTNP_ID ) USING INDEX DMRPMCOR.CSTMR_OU_RLTNP_IDX_2;
ALTER TABLE DMRPMCOR.IP_X_TX_TP_RLTNP ADD CONSTRAINT IP_X_TX_TP_RLTNP_PK PRIMARY KEY ( EFF_DT,IP_ID,RANK,TX_TP_ID ) USING INDEX DMRPMCOR.IP_X_TX_TP_RLTNP_PK;
ALTER TABLE DMRPMCOR.CST_FRGN_CCY_OPRN ADD CONSTRAINT CST_FRGN_CCY_OPRN_PK PRIMARY KEY ( CSTMR_ID,FRGN_CCY_AC_NUM,FRGN_CCY_PD_TP_ID,OPRN_FRGN_CCY_TP_ID ) USING INDEX DMRPMCOR.CST_FRGN_CCY_OPRN__IDX;
ALTER TABLE DMRPMCOR.IP_X_SRC_STM_RLTNP ADD CONSTRAINT IP_X_SRC_STM_RLTNP_PK PRIMARY KEY ( EFF_DT,IP_ID,OU_ID,SRC_STM_ID ) USING INDEX DMRPMCOR.IP_X_SRC_STM_RLTNP_PK;
ALTER TABLE DMRPMCOR.LO_X_SRC_STM_RLTNP ADD CONSTRAINT LO_X_SRC_STM_RLTNP_PK PRIMARY KEY ( OU_ID,SCDY_CODE,SRC_STM_ID ) USING INDEX DMRPMCOR.LO_X_SRC_STM_RLTNP_PK;
ALTER TABLE DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP ADD CONSTRAINT CL_X_OU_X_CSTMR_RLTNP_PK PRIMARY KEY ( CL_X_OU_X_CSTMR_RLTNP_TP_ID,CSTMR_X_OU_RLTNP_ID ) USING INDEX DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP_PK;

ALTER TABLE DMRPMCOR.CD ADD CONSTRAINT CD_CD_TP_FK FOREIGN KEY ( CNDTN_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CD ADD CONSTRAINT CD_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_LO_FK FOREIGN KEY ( DOC_ISSU_CITY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_LNG_FK FOREIGN KEY ( LNG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_LO_FK1 FOREIGN KEY ( DOC_ISSU_CTY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_NTY_FK FOREIGN KEY ( NTY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_ACTN_FK FOREIGN KEY ( BLCKLIST_ACTN_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IP_TP_FK FOREIGN KEY ( IP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_CL_VAL_FK FOREIGN KEY ( IDENTN_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IDY_CL_FK FOREIGN KEY ( ECN_AVY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_TXP_TP_FK FOREIGN KEY ( TPY_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_CL_VAL_FK1 FOREIGN KEY ( DOC_ST_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IDY_CL_FK1 FOREIGN KEY ( CIIU_IDY_CL_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IDY_CL_FK2 FOREIGN KEY ( SUB_CIIU_IDY_CL_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_WHLD_TP_FK FOREIGN KEY ( WHLD_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_BSN_SECT_FK FOREIGN KEY ( BSN_SECT_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_SALUT_TP_FK FOREIGN KEY ( SALUT_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_TPY_CLSS_FK FOREIGN KEY ( TPY_CLSS_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_COL_RSDNT_FK FOREIGN KEY ( COL_RSDNT_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IP_GRP_TP_FK FOREIGN KEY ( IP_GRP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_CR_RSK_RTG_FK FOREIGN KEY ( INR_IP_CR_RSK_RTG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IP_TAX_RPT_FK FOREIGN KEY ( IP_TAX_RPT_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IP_X_IP_TP_FK FOREIGN KEY ( PRIM_RLN_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IVA_RGM_TP_FK FOREIGN KEY ( IVA_RGM_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_ORG_ENT_TP_FK FOREIGN KEY ( ORG_ENT_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_COM_ATTD_TP_FK FOREIGN KEY ( COM_ATTD_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_DCSN_TAK_TP_FK FOREIGN KEY ( DCSN_TAK_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_DOC_VLD_RSP_FK FOREIGN KEY ( DOC_VLD_RSP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_IVA_RSPL_TP_FK FOREIGN KEY ( IVA_RSPL_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_ORG_ENT_TP_FK1 FOREIGN KEY ( DCNT_STE_ENT_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_ORG_ENT_TP_FK2 FOREIGN KEY ( STE_ENT_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_BSN_SUB_SECT_FK FOREIGN KEY ( BSN_SUB_SECT_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_OUTDT_INF_TP_FK FOREIGN KEY ( OUTDT_INF_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_PREF_CTC_MTH_FK FOREIGN KEY ( PREF_CTC_MTH_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_TAX_SLF_WHLD_FK FOREIGN KEY ( TAX_SLF_WHLD_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_VIN_RSK_FCTR_FK FOREIGN KEY ( VIN_RSK_FCTR_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP ADD CONSTRAINT IP_REG_INST_MOND_FK FOREIGN KEY ( REG_INST_MOND_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.LO ADD CONSTRAINT LO_LO_FK FOREIGN KEY ( PRN_LO_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.LO ADD CONSTRAINT LO_LO_TP_FK FOREIGN KEY ( LO_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.LO ADD CONSTRAINT LO_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.OU ADD CONSTRAINT OU_IP_FK FOREIGN KEY ( OU_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.OU ADD CONSTRAINT OU_OU_FK FOREIGN KEY ( PRN_OU_IP_ID ) REFERENCES DMRPMCOR.OU ( OU_ID );
ALTER TABLE DMRPMCOR.OU ADD CONSTRAINT OU_ORG_FK FOREIGN KEY ( ORG_ID ) REFERENCES DMRPMCOR.ORG ( ORG_ID );
ALTER TABLE DMRPMCOR.OU ADD CONSTRAINT OU_OU_FCN_TP_FK FOREIGN KEY ( OU_FCN_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.OU ADD CONSTRAINT OU_OU_LCS_TP_FK FOREIGN KEY ( OU_LCS_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.OU ADD CONSTRAINT OU_OU_STC_TP_FK FOREIGN KEY ( OU_STC_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.OU ADD CONSTRAINT OU_LINE_OF_BSN_FK FOREIGN KEY ( LOB_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CNL ADD CONSTRAINT CNL_CNL_FK FOREIGN KEY ( CNL_PRN_ID ) REFERENCES DMRPMCOR.CNL ( CNL_ID );
ALTER TABLE DMRPMCOR.CNL ADD CONSTRAINT CNL_CNL_TP_FK FOREIGN KEY ( CNL_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CNL ADD CONSTRAINT CNL_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.CNL ADD CONSTRAINT CNL_CNL_LCS_TP_FK FOREIGN KEY ( CNL_LCS_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.EMP ADD CONSTRAINT EMP_OU_FK FOREIGN KEY ( OU_ID ) REFERENCES DMRPMCOR.OU ( OU_ID );
ALTER TABLE DMRPMCOR.EMP ADD CONSTRAINT EMP_IDV_FK FOREIGN KEY ( IDV_ID ) REFERENCES DMRPMCOR.IDV ( IDV_ID );
ALTER TABLE DMRPMCOR.EMP ADD CONSTRAINT EMP_OU_FK1 FOREIGN KEY ( ACG_OU_ID ) REFERENCES DMRPMCOR.OU ( OU_ID );
ALTER TABLE DMRPMCOR.EMP ADD CONSTRAINT EMP_EP_TP_FK FOREIGN KEY ( EMP_POS_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.EMP ADD CONSTRAINT EMP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.EMP ADD CONSTRAINT EMP_EMP_LCS_TP_FK FOREIGN KEY ( EMP_LCS_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_IP_FK FOREIGN KEY ( IDV_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_CTY_FK FOREIGN KEY ( CTY_BRTH_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_GND_FK FOREIGN KEY ( GND_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_CITY_FK FOREIGN KEY ( CITY_BRTH_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_CTF_TP_FK FOREIGN KEY ( CTF_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_DEATH_ST_FK FOREIGN KEY ( DEATH_ST_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_UCPBL_TP_FK FOREIGN KEY ( UCPBL_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_IDV_IDY_CL_FK FOREIGN KEY ( IDV_IDY_CL_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_IDV_OCP_TP_FK FOREIGN KEY ( IDV_OCP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_SOC_ECN_CGY_FK FOREIGN KEY ( SOCIO_ECN_CGY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_STDY_LVL_TP_FK FOREIGN KEY ( STDY_LVL_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_IDV_EMP_ST_TP_FK FOREIGN KEY ( IDV_EMP_ST_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_IDV_HLT_ST_TP_FK FOREIGN KEY ( IDV_HLT_ST_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV ADD CONSTRAINT IDV_IDV_MAR_ST_TP_FK FOREIGN KEY ( IDV_MAR_ST_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.ORG ADD CONSTRAINT ORG_IP_FK FOREIGN KEY ( ORG_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.ORG ADD CONSTRAINT ORG_ORG_FK FOREIGN KEY ( ORG_CRPT_PRN_ID ) REFERENCES DMRPMCOR.ORG ( ORG_ID );
ALTER TABLE DMRPMCOR.ORG ADD CONSTRAINT ORG_ORG_PPS_FK FOREIGN KEY ( ORG_PPS_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.ORG ADD CONSTRAINT ORG_GEO_AREA_FK FOREIGN KEY ( INC_ORG_GEO_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.ORG ADD CONSTRAINT ORG_ORG_LAW_TP_FK FOREIGN KEY ( ORG_LAW_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.ORG ADD CONSTRAINT ORG_ORG_ECN_ITN_FK FOREIGN KEY ( ORG_ECN_ITN_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.RATE ADD CONSTRAINT RATE_CD_FK FOREIGN KEY ( RATE_ID ) REFERENCES DMRPMCOR.CD ( CNDTN_ID );
ALTER TABLE DMRPMCOR.RATE ADD CONSTRAINT RATE_RATE_FK FOREIGN KEY ( REFR_RATE_ID ) REFERENCES DMRPMCOR.RATE ( RATE_ID );
ALTER TABLE DMRPMCOR.RATE ADD CONSTRAINT RATE_RATE_TP_FK FOREIGN KEY ( RATE_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_IP_FK FOREIGN KEY ( CSTMR_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_OU_FK FOREIGN KEY ( PRIM_BR_ID ) REFERENCES DMRPMCOR.OU ( OU_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CNL_FK FOREIGN KEY ( CTC_CNL_ID ) REFERENCES DMRPMCOR.CNL ( CNL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CTY_FK FOREIGN KEY ( FND_ORIG_CTY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CITY_FK FOREIGN KEY ( FND_ORIG_CITY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CNL_FK1 FOREIGN KEY ( UDT_CNL_ID ) REFERENCES DMRPMCOR.CNL ( CNL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CITY_FK1 FOREIGN KEY ( CITY_FILN_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_CGY_FK FOREIGN KEY ( CST_CGY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_FND_ORIG_FK FOREIGN KEY ( FND_ORIG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_GEO_AREA_FK FOREIGN KEY ( GEO_AREA_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_PBLC_EXD_FK FOREIGN KEY ( PBLC_EXD_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_PTY_ORIG_FK FOREIGN KEY ( PTY_ORIG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CLVALTOTC_FK FOREIGN KEY ( TOTAL_COST_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CTC_LO_TP_FK FOREIGN KEY ( CTC_LO_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_LCS_TP_FK FOREIGN KEY ( CSTMR_LCS_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_SOC_STL_TP_FK FOREIGN KEY ( SOC_STL_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_MKT_SEG_FK FOREIGN KEY ( CSTMR_MKT_SEG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_PBLC_EXD_FE_FK FOREIGN KEY ( PBLC_EXD_FE_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_SMS_CTC_AHR_FK FOREIGN KEY ( SMS_CTC_AHR_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_MKT_SEG_FK1 FOREIGN KEY ( CSTMR_MKT_SUB_SEG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_RLTNP_ST_FK FOREIGN KEY ( CST_RLTNP_ST_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_FNC_IMT_PD_F_FK FOREIGN KEY ( FNC_IMT_PD_F_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_FRGN_EXG_BKR_FK FOREIGN KEY ( FRGN_EXG_BKR_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_INTVN_LAW_TP_FK FOREIGN KEY ( INTVN_LAW_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_SLFT_RSK_RTG_FK FOREIGN KEY ( SLFT_RSK_RTG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_RLTNP_ST_FK1 FOREIGN KEY ( CST_RLTNP_AVY_ST_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_AC_STMT_DLV_TP_FK FOREIGN KEY ( AC_STMT_DLV_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_EMP_EXN_TP_FK FOREIGN KEY ( CST_EMP_EXN_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_RET_AC_STMT_TP_FK FOREIGN KEY ( RET_AC_STMT_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_PTNL_VAL_TP_FK FOREIGN KEY ( CST_PTNL_VAL_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_TRN_MKT_SEG_FK FOREIGN KEY ( CSTMR_MKT_TRNSV_SEG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_PCRMT_PCS_CL_TP_FK FOREIGN KEY ( PCRMT_PCS_CL_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_SPCL_CR_ADMN_TP_FK FOREIGN KEY ( SPCL_CR_ADMN_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_SPCL_PRGM_TP_FK FOREIGN KEY ( CST_SPCL_PRGM_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CST_STRTG_VAL_TP_FK FOREIGN KEY ( CST_STRTG_VAL_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_CSTMR_RTF_WHLD_TP_FK FOREIGN KEY ( CSTMR_RTF_WHLD_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_EMAIL_ADR_CTC_AHR_FK FOREIGN KEY ( EMAIL_ADR_CTC_AHR_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CSTMR ADD CONSTRAINT CSTMR_EXMPT_CASH_OPRN_STMT_FK FOREIGN KEY ( EXMPT_CASH_OPRN_STMT_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_SCM ADD CONSTRAINT CL_SCM_CL_SCM_FK FOREIGN KEY ( CL_SUP_SCM_ID ) REFERENCES DMRPMCOR.CL_SCM ( CL_SCM_ID );
ALTER TABLE DMRPMCOR.CL_SCM ADD CONSTRAINT CL_SCM_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.CL_TSL ADD CONSTRAINT CL_TSL_LNG_FK FOREIGN KEY ( LNG_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_TSL ADD CONSTRAINT CL_TSL_CL_VAL_FK FOREIGN KEY ( CL_TSL_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_TSL ADD CONSTRAINT CL_TSL_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.CL_VAL ADD CONSTRAINT CL_VAL_CL_SCM_FK FOREIGN KEY ( ROOT_CL_SCM_ID ) REFERENCES DMRPMCOR.CL_SCM ( CL_SCM_ID );
ALTER TABLE DMRPMCOR.CL_VAL ADD CONSTRAINT CL_VAL_CL_VAL_FK FOREIGN KEY ( GRP_CL_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_VAL ADD CONSTRAINT CL_VAL_CL_SCM_FK1 FOREIGN KEY ( CL_SCM_ID ) REFERENCES DMRPMCOR.CL_SCM ( CL_SCM_ID );
ALTER TABLE DMRPMCOR.CL_VAL ADD CONSTRAINT CL_VAL_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.ELC_ADR ADD CONSTRAINT ELC_ADR_ADR_FK FOREIGN KEY ( ELC_ADR_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.ELC_ADR ADD CONSTRAINT ELC_ADR_ELC_ADR_TP_FK FOREIGN KEY ( ELC_ADR_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.ELC_ADR ADD CONSTRAINT ELC_ADR_TEL_DVC_TP_FK FOREIGN KEY ( TEL_DVC_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.MSR_PRD ADD CONSTRAINT MSR_PRD_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.MSR_PRD ADD CONSTRAINT MSR_PRD_MSR_PRD_TP_FK FOREIGN KEY ( TM_PRD_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.PST_ADR ADD CONSTRAINT PST_ADR_ADR_FK FOREIGN KEY ( PST_ADR_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.PST_ADR ADD CONSTRAINT PST_ADR_CTY_FK FOREIGN KEY ( CTY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.PST_ADR ADD CONSTRAINT PST_ADR_STE_FK FOREIGN KEY ( STE_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.PST_ADR ADD CONSTRAINT PST_ADR_CITY_FK FOREIGN KEY ( CITY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.EXG_RATE ADD CONSTRAINT EXG_RATE_CCY_FK FOREIGN KEY ( SCD_CCY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.EXG_RATE ADD CONSTRAINT EXG_RATE_CCY_FK1 FOREIGN KEY ( FRST_CCY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.EXG_RATE ADD CONSTRAINT EXG_RATE_RATE_FK FOREIGN KEY ( EXG_RATE_ID ) REFERENCES DMRPMCOR.RATE ( RATE_ID );
ALTER TABLE DMRPMCOR.IDV_PRFL ADD CONSTRAINT IDV_PRFL_CCY_FK FOREIGN KEY ( DNMN_CCY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IDV_PRFL ADD CONSTRAINT IDV_PRFL_IDV_FK FOREIGN KEY ( IDV_ID ) REFERENCES DMRPMCOR.IDV ( IDV_ID );
ALTER TABLE DMRPMCOR.IDV_PRFL ADD CONSTRAINT IDV_PRFL_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.INT_RATE ADD CONSTRAINT INT_RATE_RATE_FK FOREIGN KEY ( INT_RATE_ID ) REFERENCES DMRPMCOR.RATE ( RATE_ID );
ALTER TABLE DMRPMCOR.INT_RATE ADD CONSTRAINT INT_RATE_INT_TP_FK FOREIGN KEY ( INT_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.INT_RATE ADD CONSTRAINT INT_RATE_INT_CTN_CLC_PRD_FK FOREIGN KEY ( INT_CLC_PRD_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.ORG_PRFL ADD CONSTRAINT ORG_PRFL_CCY_FK FOREIGN KEY ( DNMN_CCY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.ORG_PRFL ADD CONSTRAINT ORG_PRFL_ORG_FK FOREIGN KEY ( ORG_ID ) REFERENCES DMRPMCOR.ORG ( ORG_ID );
ALTER TABLE DMRPMCOR.ORG_PRFL ADD CONSTRAINT ORG_PRFL_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.PRDC_ITRV ADD CONSTRAINT PRDC_ITRV_CD_FK FOREIGN KEY ( PRDC_ITRV_ID ) REFERENCES DMRPMCOR.CD ( CNDTN_ID );
ALTER TABLE DMRPMCOR.PRDC_ITRV ADD CONSTRAINT PRDC_ITRV_UOM_FK FOREIGN KEY ( UOM_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_CL_RLTNP ADD CONSTRAINT CL_X_CL_RLTNP_CL_VAL_FK FOREIGN KEY ( OBJ_CL_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_CL_RLTNP ADD CONSTRAINT CL_X_CL_RLTNP_CL_VAL_FK1 FOREIGN KEY ( SBJ_CL_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_CL_RLTNP ADD CONSTRAINT CL_X_CL_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.CL_X_CL_RLTNP ADD CONSTRAINT CL_X_CL_RLTNP_CL_X_CL_TP_FK FOREIGN KEY ( CL_X_CL_RLTNP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_IP_RLTNP ADD CONSTRAINT CL_X_IP_RLTNP_IP_FK FOREIGN KEY ( IP_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.CL_X_IP_RLTNP ADD CONSTRAINT CL_X_IP_RLTNP_CL_VAL_FK FOREIGN KEY ( CV_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_IP_RLTNP ADD CONSTRAINT CL_X_IP_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.CL_X_IP_RLTNP ADD CONSTRAINT CL_X_IP_RLTNP_CL_X_IP_TP_FK FOREIGN KEY ( CL_X_IP_RLTNP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_OU_RLTNP ADD CONSTRAINT CL_X_OU_RLTNP_OU_FK FOREIGN KEY ( OU_ID ) REFERENCES DMRPMCOR.OU ( OU_ID );
ALTER TABLE DMRPMCOR.CL_X_OU_RLTNP ADD CONSTRAINT CL_X_OU_RLTNP_CL_VAL_FK FOREIGN KEY ( CL_VAL_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_OU_RLTNP ADD CONSTRAINT CL_X_OU_RLTNP_CL_VAL_FK1 FOREIGN KEY ( CL_X_OU_RLTNP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_OU_RLTNP ADD CONSTRAINT CL_X_OU_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT CSTMR_CTC_TP_FK FOREIGN KEY ( CTC_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT IP_X_IP_RLTNP_IP_FK FOREIGN KEY ( OBJ_IP_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT IP_X_IP_RLTNP_IP_FK1 FOREIGN KEY ( SBJ_IP_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT IP_X_IP_RLTNP_POS_FK FOREIGN KEY ( POS_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT IP_X_IP_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT IP_X_IP_RLTNP_IP_X_IP_TP_FK FOREIGN KEY ( IP_X_IP_RLTNP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT IP_X_IP_RLTNP_AREA_MGT_TP_FK FOREIGN KEY ( AREA_MGT_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP_X_IP_RLTNP ADD CONSTRAINT IP_X_IP_RLTNP_FNC_IMT_A_TP_FK FOREIGN KEY ( FNC_IMT_AHR_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP_X_LO_RLTNP ADD CONSTRAINT IP_X_LO_RLTNP_IP_FK FOREIGN KEY ( IP_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.IP_X_LO_RLTNP ADD CONSTRAINT IP_X_LO_RLTNP_LO_FK FOREIGN KEY ( LO_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.IP_X_LO_RLTNP ADD CONSTRAINT IP_X_LO_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.IP_X_LO_RLTNP ADD CONSTRAINT IP_X_LO_RLTNP_IP_X_LO_TP_FK FOREIGN KEY ( IP_X_LO_RLTNP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.LO_X_CL_RLTNP ADD CONSTRAINT LO_X_CL_RLTNP_LO_FK FOREIGN KEY ( LO_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.LO_X_CL_RLTNP ADD CONSTRAINT LO_X_CL_RLTNP_CL_VAL_FK FOREIGN KEY ( CV_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.LO_X_CL_RLTNP ADD CONSTRAINT LO_X_CL_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.LO_X_CL_RLTNP ADD CONSTRAINT LO_X_CL_RLTNP_LO_X_CL_TP_FK FOREIGN KEY ( LO_X_CL_RLTNP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.LO_X_LO_RLTNP ADD CONSTRAINT LO_X_LO_RLTNP_LO_FK FOREIGN KEY ( SBJ_LO_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.LO_X_LO_RLTNP ADD CONSTRAINT LO_X_LO_RLTNP_LO_FK1 FOREIGN KEY ( OBJ_LO_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.LO_X_LO_RLTNP ADD CONSTRAINT LO_X_LO_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.LO_X_LO_RLTNP ADD CONSTRAINT LO_X_LO_RLTNP_LO_X_LO_TP_FK FOREIGN KEY ( LO_X_LO_RLTNP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CTY_X_CCY_RLTNP ADD CONSTRAINT CTY_X_CCY_RLTNP_CCY_FK FOREIGN KEY ( CCY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CTY_X_CCY_RLTNP ADD CONSTRAINT CTY_X_CCY_RLTNP_CTY_FK FOREIGN KEY ( CTY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.CSTMR_X_OU_RLTNP ADD CONSTRAINT CSTMR_X_OU_RLTNP_OU_FK FOREIGN KEY ( OU_ID ) REFERENCES DMRPMCOR.OU ( OU_ID );
ALTER TABLE DMRPMCOR.CSTMR_X_OU_RLTNP ADD CONSTRAINT CSTMR_X_OU_RLTNP_CSTMR_FK FOREIGN KEY ( CSTMR_ID ) REFERENCES DMRPMCOR.CSTMR ( CSTMR_ID );
ALTER TABLE DMRPMCOR.CSTMR_X_OU_RLTNP ADD CONSTRAINT CSTMR_X_OU_RLTNP_CTC_CNL_FK FOREIGN KEY ( CTC_CNL_ID ) REFERENCES DMRPMCOR.CNL ( CNL_ID );
ALTER TABLE DMRPMCOR.CSTMR_X_OU_RLTNP ADD CONSTRAINT CSTMR_X_OU_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.IP_X_TX_TP_RLTNP ADD CONSTRAINT IP_X_TX_TP_RLTNP_IP_FK FOREIGN KEY ( IP_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.IP_X_TX_TP_RLTNP ADD CONSTRAINT IP_X_TX_TP_RLTNP_TX_TP_FK FOREIGN KEY ( TX_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CST_FRGN_CCY_OPRN ADD CONSTRAINT CST_FRGN_CCY_OPRN_CCY_FK FOREIGN KEY ( FRGN_CCY_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CST_FRGN_CCY_OPRN ADD CONSTRAINT CST_FRGN_CCY_OPRN_CTY_FK FOREIGN KEY ( CTY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.CST_FRGN_CCY_OPRN ADD CONSTRAINT CST_FRGN_CCY_OPRN_CITY_FK FOREIGN KEY ( CITY_ID ) REFERENCES DMRPMCOR.LO ( LO_ID );
ALTER TABLE DMRPMCOR.CST_FRGN_CCY_OPRN ADD CONSTRAINT CST_FRGN_CCY_OPRN_CSTMR_FK FOREIGN KEY ( CSTMR_ID ) REFERENCES DMRPMCOR.CSTMR ( CSTMR_ID );
ALTER TABLE DMRPMCOR.CST_FRGN_CCY_OPRN ADD CONSTRAINT CST_FRGN_CCY_OPRN_PD_TP_FK FOREIGN KEY ( FRGN_CCY_PD_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CST_FRGN_CCY_OPRN ADD CONSTRAINT CST_FRGN_CCY_OPRN_OPRN_F_FK FOREIGN KEY ( OPRN_FRGN_CCY_F_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CST_FRGN_CCY_OPRN ADD CONSTRAINT CST_FRGN_CCY_OPRN_OPRN_TP_FK FOREIGN KEY ( OPRN_FRGN_CCY_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.IP_X_SRC_STM_RLTNP ADD CONSTRAINT IP_X_SRC_STM_RLTNP_IP_FK FOREIGN KEY ( IP_ID ) REFERENCES DMRPMCOR.IP ( IP_ID );
ALTER TABLE DMRPMCOR.IP_X_SRC_STM_RLTNP ADD CONSTRAINT IP_X_SRC_STM_RLTNP_OU_FK FOREIGN KEY ( OU_ID ) REFERENCES DMRPMCOR.OU ( OU_ID );
ALTER TABLE DMRPMCOR.IP_X_SRC_STM_RLTNP ADD CONSTRAINT IP_X_SRC_STM_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.LO_X_SRC_STM_RLTNP ADD CONSTRAINT LO_X_SRC_STM_RLTNP_OU_FK FOREIGN KEY ( OU_ID ) REFERENCES DMRPMCOR.OU ( OU_ID );
ALTER TABLE DMRPMCOR.LO_X_SRC_STM_RLTNP ADD CONSTRAINT LO_X_SRC_STM_RLTNP_SRC_STM_FK FOREIGN KEY ( SRC_STM_ID ) REFERENCES DMRPMCOR.SRC_STM ( SRC_STM_ID );
ALTER TABLE DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP ADD CONSTRAINT CLXOUCSTMRRLT_CMRXOURLTNP_FK FOREIGN KEY ( CL_X_OU_X_CSTMR_RLTNP_TP_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP ADD CONSTRAINT CL_X_OU_X_CSTMRRLTNPCL_VAL_FK FOREIGN KEY ( CV_ID ) REFERENCES DMRPMCOR.CL_VAL ( CL_VAL_ID );
ALTER TABLE DMRPMCOR.CL_X_OU_X_CSTMR_RLTNP ADD CONSTRAINT CLXOUCSTMRRLTPCLXOUXCSTMRTP_FK FOREIGN KEY ( CSTMR_X_OU_RLTNP_ID ) REFERENCES DMRPMCOR.CSTMR_X_OU_RLTNP ( CSTMR_X_OU_RLTNP_ID );

